### ISSUE TITLE
Need for new release

### ISSUE THREAD

**Issue by ronaldchoi** [snok/django-auth-adfs#109]
Installed the latest version and trying to use "CREATE_NEW_USERS" as instructed in the documentation, but was hit with "not a valid configuration directive" error. Turns out it was included in the latest commit that comes after 1.3.1

I understand we can install the latest commit as such:
`pip install git+git://github.com/jobec/django-auth-adfs@41fa2b8eca8f80be9db2026a6310673f9cbde1bb`

However I reckon a new minor release would be more suitable. So any chance we can release a 1.3.2 to bring the latest changes up to date?

**Comment by JonasKs** [comment]
Hi. `1.4.0` is released.
