### ISSUE TITLE
Add email & profile scopes

### ISSUE THREAD

**Issue by snowman2** [snok/django-auth-adfs#111]
https://github.com/jobec/django-auth-adfs/blob/93bcb3ff262ae92b3bae2858a34fb09977f9a9a4/django_auth_adfs/config.py#L322

Change to: `"openid email profile"`

**Comment by JonasKs** [comment]
Would you be up to raise a PR for this?

**Comment by snowman2** [comment]
I am now using django-allauth as it supports other providers I need as well. I wish you the best with this package.
