### ISSUE TITLE
Custom failure handler?

### ISSUE THREAD

**Issue by peterfarrell** [snok/django-auth-adfs#112]
We'd like to customize the failure page. Would you be open to a pull request that allows you to optionally set a path to view function where both the view function can customized in additional to which template is used?  If not defined, the current django-adfs-auth failure would be used.

Something similar to how DjangoSAML2 does it:
https://github.com/knaperek/djangosaml2#custom-error-handler

```
AUTH_ADFS = {
    "FAILURE_RESPONSE_VIEW_FUNCTION": ''python.path.to.your.template_failure"
}
```

This should be a view which takes a request, optional exception which occurred and status code, and returns a response to serve the user. The default implementation looks like this:

```
def template_failure(request, exception=None, **kwargs):
    """ Renders a simple template with an error message. """
    return render(request, 'django_adfs_auth/login_error.html', {'exception': exception}, status=kwargs.get('status', 403))
```

**Comment by JonasKs** [comment]
Hi. Are you still up for making a PR for this?

**Comment by peterfarrell** [comment]
@JonasKs yes

**Comment by peterfarrell** [comment]
@JonasKs  #136 is ready for review. Includes tests and updated the documentation.

**Comment by peterfarrell** [comment]
Closing this issue since it was a question on if a PR would be accepted.
