### ISSUE TITLE
Has anyone completed an integration w/ Azure Active Directory? Docs Screenshots are old and outdated.

### ISSUE THREAD

**Issue by svpernova09** [snok/django-auth-adfs#114]
Using this as a guide: https://django-auth-adfs.readthedocs.io/en/latest/azure_ad_config_guide.html#step-1-register-an-application

I created the 2 applications, but:

> The value of identifierUris is the value for the RELYING_PARTY_ID and AUDIENCE setting.

This value was blank in my Manifests. 

> Fill in a name again an this time select the Native type.

Website / Native types aren't being used anymore. what's the proper way?

> The native application now needs to be given permission to access the web application we created earlier. Click the Settings button and then select Required permissions

How does this translate to the new UI? I can't figure out how to give my Native registration access to the other app registration.

Clicking on "API Permissions" doesn't provide a search option to find my first app registration.

![image](https://user-images.githubusercontent.com/967362/98596697-6daa0180-229d-11eb-8289-9e67ea06264f.png)

This is as far as I've been able to get. I only assume I'm going to hit more/the same bumps further in the guide.

**Comment by marlonpatrick** [comment]
I've the same problems with Azure AD configuration.

Other thing I have difficulties is the configuration for an SAP + Django Rest Framework in Azure. Is not clear to me what apps to register and your configurations.

**Comment by marlonpatrick** [comment]
I managed to configure the following scenario: angular application + backend application (django rest framework).

1 - Configure the Angular frontend as explained [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-app-registration) and [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-angular). To do this, you will need to register an application with Azure AD. In my case, I used msal.js 1 (implicit flow).

2 - Register a Web application in Azure AD which will represent the Django Rest backend. After registering the application, access the "Expose an API" menu and register a scope. For example:

**Scope**: api://12345678-1234-1234-1234-123456789012/full-access # Azure itself already generates a UUID
**Who can consent**: Admins and users

3 - Access the registered application for the frontend, then access the API Permissions menu. Click on "Add a permission". Go to the "APIs my organization uses" tab. Search and select by the name of the application registered for the backend and select the scope created earlier. Save it.

4 - Go back in the registered application to the backend, click on the Manifest menu and obtain the value in the "identifierUris" field which will be used in the RELYING_PARTY_ID and AUDIENCE settings.
**Note that this "identifierUris" field is only populated at this time**.

5 - Settings in the Django application:

```
INSTALLED_APPS = [
   'etc'
    'rest_framework',
    'django_auth_adfs'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
  'django_auth_adfs.rest_framework.AdfsAccessTokenAuthentication',
    ],
}

AUTHENTICATION_BACKENDS = [
    'django_auth_adfs.backend.AdfsAccessTokenBackend'
]

AUTH_ADFS = {
    "TENANT_ID": "12345678-1234-1234-1234-123456789012",
    "CLIENT_ID": "12345678-1234-1234-1234-123456789012", #Client ID from app registered for frontend in Azure AD
    "RELYING_PARTY_ID": "api: // 12345678-1234-1234-1234-123456789012", # identifierUris from app registered for backend in Azure AD
    "AUDIENCE": "api: // 075a208d-7413-40b9-acda-07688c2c2f1f", # identifierUris from app registered for backend in Azure AD
}

```

The guide described at https://django-auth-adfs.readthedocs.io/en/latest/azure_ad_config_guide.html is a little outdated and with some steps out of order, but it is still useful. Consider that Web app / API is equivalent to django rest application and Native app is equivalent to frontend app.

**Comment by JonasKs** [comment]
@marlonpatrick , it would be nice if you could refresh the guide and screenshots in the docs and make a PR.

**Comment by JonasKs** [comment]
Hi,

Did you ever get a chance to look at this @marlonpatrick ? :smile:

**Comment by afga97** [comment]
Hello, could I get your help, I have followed the integration of django and rest framework trying to send an acces_token but my APIView are not protected and this jwt acces issued by azure is not validated, could you help me achieve it

@JonasKs  @marlonpatrick

**Comment by afga97** [comment]
@marlonpatrick 

Hello

I am following your configuration but at the moment of sending the acces_token I get the following error in the backend

Could you help me achieve it?

![image](https://user-images.githubusercontent.com/41203767/104638926-ce2a3600-5674-11eb-8e5b-4f6b0551c7c8.png)

**Comment by JonasKs** [comment]
Hi @afga97, see #118 for a work around. 
The fix is in #120 , but I haven’t been able to look at it today, unfortunately.

**Comment by JonasKs** [comment]
Closing this in favor or #81 .

There is also a PR (#123) to fix docs.

**Comment by afga97** [comment]
@JonasKs 

Hi 

I was updating the version and I no longer present the error, I have the following problem but I don't know what I'm doing wrong, you could give me a signal

django-auth-adfs = 1.5.0
PyJwt = 2.0.1

Beforehand thanks for the information

![image](https://user-images.githubusercontent.com/41203767/104966737-abb75600-59af-11eb-9d86-b1417bc2f1f3.png)

**Comment by JonasKs** [comment]
Hi @afga97, please create a separate issue for this. Remember to enable debug (see the docs under Troubleshooting) and post the entire stack trace, not just the last two lines. 😊
