### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by Seykotron** [snok/django-auth-adfs#116]
If some user has no UPN there raises an error, the code should check if that claim exist's before try to asign it as an Username

https://github.com/jobec/django-auth-adfs/blob/93bcb3ff262ae92b3bae2858a34fb09977f9a9a4/django_auth_adfs/backend.py#L123

Thank you!

**Comment by JonasKs** [comment]
Agree.  Would you like to raise a PR?

**Comment by Seykotron** [comment]
Yes, im a bit bussy right now, but I can raise a PR yep, proud to take part of this proyect 👍

**Comment by JonasKs** [comment]
Awesome. Let me know if you need any help!
