### ISSUE TITLE
PyJWT 2.0 not compatible

### ISSUE THREAD

**Issue by MAndersenNano** [snok/django-auth-adfs#118]
The current version is not compatible with version 2.0 of PyJWT, since jwt.ExpiredSignature has been renamed to jwt.ExpiredSignatureError (used in line 17 in backend.py). 

Suggested suggestions:
- Either realign with PyJWT 2.0
- Cahnge install_requires in setup.py from **'pyjwt >= 1.0.1',** to **'pyjwt >= 1.0.1, < 2.0',**

**Comment by ingvaldlorentzen** [comment]
A temporary workaround for people facing this issue is to pin the `PyJWT` package to v1 in your own dependency files.  
E.g. if you use `requirements.txt`, adding `PyJWT==1.7.1` should solve the problem.

**Comment by JonasKs** [comment]
PyPI version released.
