### ISSUE TITLE
Login Failed.

### ISSUE THREAD

**Issue by gauravdutt13** [snok/django-auth-adfs#122]
Hi ,
I have configured my django cms using ADFS, nginx as web server to and gunicorn to run the app.
I am observing different behaviour after integrating with ADFS.

1. if a user is logged in and if he logs out and tries to login again , he gets login failed. 
2.  Sometimes a new user gets created but sometimes it fails to create new user , again with the same error login failed.
3. if a user is logged into one browser window and tries to login the cms console in another browser then again login fails.
4.  And in above process , user permission also gets lost . for example if a user is having staff and superuser access , he just looses both of the access.

Now below is the configuration part :
1. entire installation is running on a container , and django cms is accessible over https .
2. nginx is used to redirect http traffic to https.
3.  ADFS is installed using 
```
pip install django-auth-adfs
```
4. Some part of settings.py 

```
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

AUTH_ADFS = {
    "SERVER": "xxxxxxxxxxxxxxxxx",
    "CLIENT_ID": "xxxxxxxxxxxxxxxxxx",
    "RELYING_PARTY_ID": "xxxxxxxxxxxxxxxxxxx",
    "AUDIENCE": "xxxxxxxxxxxxxxxxxxx",
    "CLAIM_MAPPING": {"first_name": "given_name",
                      "last_name": "family_name",
                      "email": "email"},
    "USERNAME_CLAIM": "winaccountname",
    "GROUP_CLAIM": "group",
    "BOOLEAN_CLAIM_MAPPING": {"is_staff": True,
                              "is_superuser": True},

}
 
INSTALLED_APPS = [
    'django_auth_adfs',
....
]
LOGIN_URL = "django_auth_adfs:login"
LOGIN_REDIRECT_URL = "/en/?edit"

AUTHENTICATION_BACKENDS = [
    'django_auth_adfs.backend.AdfsAuthCodeBackend',
]

```

# nginx conf

```
upstream cms {
    server localhost:5000;
}

server {
 
    listen 443 ssl;
    if ($http_x_forwarded_proto != 'https') {
      return 301 https://$host$request_uri;
     }
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    server_tokens off;
    ssl_certificate /etc/ssl/cms.crt;
    ssl_certificate_key /etc/ssl/cms.key;
    access_log /var/log/nginx-access.log;
    error_log /var/log/nginx-error.log;  
    charset     utf-8;
    client_max_body_size 4096M;
    
    location /media  {
        alias /apps/static_media_files/media;
        client_max_body_size 4096M;
    }

    # your Django project's static files - amend as required
    location /static {
        alias /apps/static_media_files/static;
    }

    location / {
        proxy_pass http://cms;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    }

}
```

Issue is sometimes user is able to login , but sometimes they get login failed error. even new user creation doesn't happen automatically and user gets login failed but sometimes it allows new user creation as well .
in logs I can see - 
```
ADFS server returned an error: MSIS9612: The authorization code received in 'code' parameter is invalid.
```

**Comment by JonasKs** [comment]
Hi,  
Please enable debug logging as described in the documentation and provide a full output of the stack trace and logs.

**Comment by gauravdutt13** [comment]
@JonasKs I have added below code in settings.py 

```import logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '../tmp/debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
```
attaching debug.log for your reference.
[debug.log](https://github.com/snok/django-auth-adfs/files/5878045/debug.log)

**Comment by sondrelg** [comment]
Do you still need help with this @gauravdutt13? If so, feel free to reopen 👍
