### ISSUE TITLE
Role Based Access Control - Feature Request

### ISSUE THREAD

**Issue by jacardbr** [snok/django-auth-adfs#141]
Hi, any chance to implement Azure AD - RBAC?

Bests

**Comment by JonasKs** [comment]
Hi,  

Please correct me if I'm wrong (I'm not an Azure user), but isn't RBAC just a way to add roles in the claim? So when you add a scope, this will be returned in the `jwt` under `roles`?   
If not, can you provide me with examples on how the `jwt` token will look with RBAC compared to a normal one?

**Comment by jacardbr** [comment]
On JWT decoded, we have a key roles with a list of roles matched:
`
"roles": [
"system.admin"
],
`
and on Django side, we have to use this role to access control,
eg. 
if this session have role "admin" on JWT, then this user should have admin privilege.

**Comment by JonasKs** [comment]
On phone so forgive my formatting, but this should work: 
```py
AUTH_ADFS = {
    ...
    'GROUPS_CLAIM': 'roles',
    "MIRROR_GROUPS': True,
    "GROUP_TO_FLAG_MAPPING": {"is_staff": "System.staff",
                              "is_superuser": "Systems.admin"},
```

Docs: https://django-auth-adfs.readthedocs.io/en/latest/settings_ref.html#group-to-flag-mapping

**Comment by jacardbr** [comment]
Nice job! I gonna try.

> On phone so forgive my formatting, but this should work:
> 
> ```python
> AUTH_ADFS = {
>     ...
>     "GROUPS_CLAIM": "roles",
>     "MIRROR_GROUPS": True,
>     "GROUP_TO_FLAG_MAPPING": {"is_staff": "system.staff",
>                               "is_superuser": "system.admin"},
> ```
> 
> Docs: https://django-auth-adfs.readthedocs.io/en/latest/settings_ref.html#group-to-flag-mapping

**Comment by JonasKs** [comment]
Any status on this? :relaxed:

**Comment by JonasKs** [comment]
Stale issue, closing.
