### ISSUE TITLE
JWT_LEEWAY listed incorrectly in documentation

### ISSUE THREAD

**Issue by dVerhees** [snok/django-auth-adfs#147]
https://django-auth-adfs.readthedocs.io/en/latest/settings_ref.html#leeway-jwt

As you can see by the above link, the name of the setting has been swapped in the documentation, it should mention JWT_LEEWAY, instead of LEEWAY-JWT.

**Comment by JonasKs** [comment]
Thank you! I'll make sure to fix this ASAP.
