### ISSUE TITLE
Django generating 'redirect_uri' as http (not S)

### ISSUE THREAD

**Issue by jacardbr** [snok/django-auth-adfs#148]
I tried to use this setting:
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
But it doesnt works for me.
Django is running on clear http port 80 and behind a aws load balancer with https.

[End User] <--443--> [AWS LB] <--80--> [DJANGO]

Is there some configuration param that I am missing?

**Comment by JonasKs** [comment]
It's impossible to help you troubleshoot without _what_ does not work for you. Full stack trace, reproduce steps and so on. 

Redirect URIs mismatching is probably a reason though, play around with that.

**Comment by JonasKs** [comment]
Also have a look in #69

**Comment by jacardbr** [comment]
I solved with this config on NGINX:
---
replaced
proxy_set_header X-Forwarded-Proto $scheme;
to
proxy_set_header X-Forwarded-Proto https;
