### ISSUE TITLE
Please update the version to v2.0

### ISSUE THREAD

**Issue by jatindergit** [snok/django-auth-adfs#155]
Hi
` def _load_openid_config(self):
        config_url = "https://{}/{}/.well-known/openid-configuration?appid={}".format(
            settings.SERVER, settings.TENANT_ID, settings.CLIENT_ID
        )`

` def _load_openid_config(self):
        config_url = "https://{}/{}/v2.0/.well-known/openid-configuration?appid={}".format(
            settings.SERVER, settings.TENANT_ID, settings.CLIENT_ID
        )`
Please update the version here or provide the version in settings if possible
Thanks

**Comment by jatindergit** [comment]
@JonasKs Please take of this too

**Comment by jatindergit** [comment]
@JonasKs I have submitted the pull request. Please let me know if anything else is needed

**Comment by sondrelg** [comment]
Seems like this was resolved in release 1.7.0 🙂
