### ISSUE TITLE
You cannot set the username field of the user model from the CLAIM_MAPPING setting. Instead use the USERNAME_CLAIM setting

### ISSUE THREAD

**Issue by jatindergit** [snok/django-auth-adfs#156]
Hi @JonasKs 

I am using custom user model in my Django REST Framework Application. My settings:
`AUTH_ADFS = {
    'TENANT_ID': '*********************',
    'AUDIENCE': ''*********************',',
    'CLIENT_ID': ''*********************',',
   'RELYING_PARTY_ID': ''*********************',',
    'USERNAME_CLAIM': 'upn',
    'LOGIN_EXEMPT_URLS': [
        '^api',  # Assuming you API is available at /api
    ],
    "CLAIM_MAPPING": {"first_name": "given_name",
                      "last_name": "family_name",
                      "email": "email"},
}`
Username field in my User model is
USERNAME_FIELD = 'email'

But I am getting:
django.core.exceptions.ImproperlyConfigured: You cannot set the username field of the user model from the CLAIM_MAPPING setting. Instead use the USERNAME_CLAIM setting.

I really dont find any way to figure out this exception in env/lib/python3.8/site-packages/django_auth_adfs/config.py

Please help
Thanks

**Comment by JonasKs** [comment]
Try removing `"email": "email"` from your `CLAIM_MAPPING`. 

The code in question:

```py
# Validate setting conflicts
usermodel = get_user_model()
if usermodel.USERNAME_FIELD in self.CLAIM_MAPPING.keys():
    raise ImproperlyConfigured("You cannot set the username field of the user model the CLAIM_MAPPING setting. Instead use the USERNAME_CLAIM setting.")

```
