### ISSUE TITLE
Invalid Access Token error when using Azure AD service principle to authenticate

### ISSUE THREAD

**Issue by Ram81** [snok/django-auth-adfs#168]
Hi,

I am trying to use this package to setup authentication using a Azure AD service principle. I am using the following [API](https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/aad/service-prin-aad-token) to get the access token.

When I make an API call using the returned access token I get the `401 Unauthorized` response with following response data
```
{
    "detail": "Invalid access token."
}
```

Settings for my django app look like this 

```
# Client secret is not public information. Should store it as an environment variable.

client_id = 'Your client id here'
cient_secret = 'Your client secret here'
tenant_id = 'Your tenant id here'


AUTH_ADFS = {
    'AUDIENCE': client_id,
    'CLIENT_ID': client_id,
    'CLIENT_SECRET': cient_secret,
    'CLAIM_MAPPING': {'first_name': 'given_name',
                      'last_name': 'family_name',
                      'email': 'upn'},
    'TENANT_ID': tenant_id,
    'RELYING_PARTY_ID': client_id,
}
```

**Comment by JonasKs** [comment]
Please enable debug settings and provide a full stack trace from terminal output. See [docs](https://django-auth-adfs.readthedocs.io/en/latest/troubleshooting.html#turn-on-django-debug-logging).

**Comment by Ram81** [comment]
@JonasKs sorry about the delay. Here's the debug log

```
O 2021-06-21 09:05:38,285 django_auth_adfs django_auth_adfs loaded settings from ADFS server.
INFO 2021-06-21 09:05:38,285 django_auth_adfs operating mode:         openid_connect
INFO 2021-06-21 09:05:38,285 django_auth_adfs authorization endpoint: https://login.microsoftonline.com/aaa/oauth2/authorize
INFO 2021-06-21 09:05:38,285 django_auth_adfs token endpoint:         https://login.microsoftonline.com/tenant_id/oauth2/token
INFO 2021-06-21 09:05:38,285 django_auth_adfs end session endpoint:   https://login.microsoftonline.com/tenant_id/oauth2/logout
INFO 2021-06-21 09:05:38,285 django_auth_adfs issuer:                 https://sts.windows.net/tenant_id/
DEBUG 2021-06-21 09:05:38,286 django_auth_adfs Received access token: <token>
INFO 2021-06-21 09:05:38,286 django_auth_adfs Algorithm not supported
Unauthorized: /api/v0/x/x/
```


API used to fetch the token is the following


```
curl --location --request POST 'https://login.microsoftonline.com/tenant_id/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=client_id' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'client_secret=secret' \
--data-urlencode 'resource=client_id'
```

**Comment by Ram81** [comment]
@JonasKs If I switch to `PyJWT==1.0.1` I get `Signature Verification Failed`

**Comment by JonasKs** [comment]
Hard for me to debug without knowing the token, algorithm or any of the other variables used. All I see is that whatever you try to decode isn't one of the [supported](https://github.com/snok/django-auth-adfs/blob/master/django_auth_adfs/backend.py#L67) algorithms.

We don't support `PyJWT==1.0.1` either. See [pyproject.toml](https://github.com/snok/django-auth-adfs/blob/master/pyproject.toml#L42)
