### ISSUE TITLE
CSRF token missing or incorrect in https request

### ISSUE THREAD

**Issue by abhiraj1289** [snok/django-auth-adfs#169]
Hi
I am having an issue related to CSRF token while using https end points.

**Issue Description** 
I am using django-auth-adfs for authentication and authorization, my application which works perfectly as expected in localhost , I am not getting any CSRF token issue in POST/PUT request.
Deployed the application in azurewebapp and the endpoints became https.
Now in azure endpoint PUT/POST request I am getting below exception
 
HTTP 403 Forbidden
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "detail": "CSRF Failed: CSRF token missing or incorrect."
}

Could you please help me to resolve the issue, your help will be much appreciated

**Comment by abhiraj1289** [comment]
@JonasKs

**Comment by JonasKs** [comment]
CSRF isn't directly related to authentication, but APIs in general. So, nothing I really can help you with.  
You should read [this](https://docs.djangoproject.com/en/3.2/ref/csrf/).
