### ISSUE TITLE
unexpected keyword argument 'allowed_methods' 

### ISSUE THREAD

**Issue by gregor-horvath** [snok/django-auth-adfs#192]
With python 3.6 and urllib3 1.25.10 and django-auth-adfs 1.9.1 I get the following in the error log:

TypeError: __init__() got an unexpected keyword argument 'allowed_methods' 

This seems to be related to 

https://github.com/snok/django-auth-adfs/pull/188/commits/84df4cb946e7384aea8e555dc83fe6d4213ed406

**Comment by sondrelg** [comment]
Thanks for reporting this @gregor-horvath. I agree, it looks like we just need to change the argument name on line 192. Would you like to open a PR with a fix? 🙂
