### ISSUE TITLE
Version 2.0 - AADSTS901002: The 'resource' request parameter is not supported.

### ISSUE THREAD

**Issue by fabianallendorf** [snok/django-auth-adfs#198]
I get this error when I set `VERSION` settings variable to `v2.0`. My backend app exposes the v2.0 endpoint. The documentation specifies that Version 2.0 is possible and even recommended for new projects. However, as soon as `build_authorization_endpoint` is called, the resource parameter is added to the query. I don't see how this works. Do I have to configure it in a different way?

I use `AdfsAuthCodeBackend` to authenticate against my backend app.

**Comment by JonasKs** [comment]
Hey. I see. I haven't been able to test out this implementation my self. :/ I'll see what I can do (but probably not before the weekend), unless you want to attempt to fix it and provide a pull request.

You'll have to [change this](https://github.com/snok/django-auth-adfs/blob/master/django_auth_adfs/config.py#L332-L338) to have a conditional check, and only add that query parameter if the version setting is not `v2`.

**Comment by fabianallendorf** [comment]
Ok, sounds reasonable, I might try it and include the changes in my PR which I have already opened.

**Comment by JonasKs** [comment]
Seems like #209 got it working. I’d try again.
