### ISSUE TITLE
group assignment/user flags in AAD

### ISSUE THREAD

**Issue by amhayes06** [snok/django-auth-adfs#200]
Hello, I'm having issues getting my user accounts to be assigned group roles and superuser permissions using Azure. My database also isn't remembering the roles if I change them manually with the django shell. Once I sign out, I lose those permissions.

In the Azure set up it says to use roles, but in the settings for GROUPS_CLAIM, it says to use groups for Azure.

I tried using both. I was able to add my user to a security group, but that didn't work. My current test was to see if I could get it to work with roles in Azure, and that also isn't working.

I'm using Postgres for the database.

```py
AUTH_ADFS = {
    'AUDIENCE': os.environ['CLIENT_ID'],
    'CLIENT_ID': os.environ['CLIENT_ID'],
    'CLIENT_SECRET': os.environ['CLIENT_SECRET'],
    'CLAIM_MAPPING': {'first_name': 'given_name',
                      'last_name': 'family_name',
                      'email': 'upn'},
    'GROUPS_CLAIM': 'roles', 
    'CREATE_NEW_USERS': False,
    'GROUP_TO_FLAG_MAPPING': {
        "is_superuser": "Exchange administrator",
        "is_staff": "Exchange administrator",
        },
    'MIRROR_GROUPS': True,
    'USERNAME_CLAIM': 'upn',
    'TENANT_ID': os.environ['TENANT_ID'],
    'RELYING_PARTY_ID': os.environ['CLIENT_ID'],
}`

**Comment by JonasKs** [comment]
Hi,

Please use three backticks and select language when formatting your code:
![bilde](https://user-images.githubusercontent.com/5310116/141095678-b4b86bdc-11cc-4477-a139-987d480e8edb.png)


> My database also isn't remembering the roles if I change them manually with the django shell

This is intended. Groups are overwritten/updated on each login.

> In the Azure set up it says to use roles, but in the settings for GROUPS_CLAIM, it says to use groups for Azure.

Decode your token through `jwt.io` or a similar site to see how the token actually looks. I think `roles` are the correct option, and you create app specific roles.

Please see how to [enable debug logs](
https://django-auth-adfs.readthedocs.io/en/latest/troubleshooting.html) and provide as much information as you can for further help. Also note that you got `'CREATE_NEW_USERS': False` in your settings. Would recommend putting that to `True` when testing.

**Comment by amhayes06** [comment]
Okay, I'll try that. Thanks!

**Comment by amhayes06** [comment]
I was able to add the role in the application registration and get it to appear in my JWT. I was having trouble because I was adding the role as a AAD, but not in the specific app. Thank you!

**Comment by JonasKs** [comment]
Glad you fixed it 😊
