### ISSUE TITLE
redirect from django to frontend with adfs access token and different hostname / port

### ISSUE THREAD

**Issue by ivan-price-acted** [snok/django-auth-adfs#208]
Hi there,

It seems my question has been asked in different ways a few times but not quite the same, most recently here:  #175 

We have a single page webapp (angular 12, no AD libraries) that attacks a DRF API.

The django-auth-adfs module is working fine against our Azure AD when used in by 'traditional' django (non-DRF) backend, however we observe that, following a successful login, the callback view (1) swallows the AD access token, and (2) limits the redirect (?next=) to urls on the same host / port.

(1) poses a problem because we can't tell our webapp what token to include in future requests, and 
(2) poses a problem because we can't send the user back to the webapp unless its the same host/port (not always the case for us)

From what i understand we need to write our own callback view to (a) capture the access token and (b) redirect to the 'frontend' host/port, with the access token and potentially with a specific state.

Am i missing something ? From what I can see the callback view is somewhat hard-coded `reverse("django_auth_adfs:callback")`, could we imagine a setting to either change it or at least provide a callback to replace the redirect [here](https://github.com/snok/django-auth-adfs/blob/91aca9b88119724e595ebcd80bb1663d76b6a675/django_auth_adfs/views.py#L56)  ?

I could prepare a PR if you think it is a sane approach.

thanks for the great project btw !

-i

**Comment by JonasKs** [comment]
Hi, I’ll reply better tomorrow (on phone now), but when using Single-Page Application (SPA) and DRF APIs all token handling should be performed directly in the frontend without any involvement of the backend. The token should then be passed as a bearer token in the header. This can be done either using the PKCE flow(preferred) or Implicit Flow. I’ve written a [blog post](https://engineering.intility.com/article/implementing-oauth2-and-openid-connect-in-your-application) about this for my [FastAPI-Azure-Auth](https://github.com/Intility/fastapi-azure-auth) library. I suggest you read that first, as it gives some insight to how things work. 

A different article can be found in the [documentation](https://django-auth-adfs.readthedocs.io/en/latest/oauth2_explained.html). This describes both using an SPA/script and the traditional way. 

I’ve also described it in a few issues, such as [this one](https://github.com/Intility/fastapi-azure-auth/issues/39#issuecomment-965346631).

**Comment by JonasKs** [comment]
I’m other words, no, this cannot be done. I’d suggest looking at [Angular-MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular) for solving token fetching for you. :) 

Resource: 
https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-angular-auth-code

**Comment by ivan-price-acted** [comment]
Thanks for your quick response @JonasKs .

Following your advice we implemented the above project and can 'login' to our Azure instance.

The part that I don't fully understand still is how to use the accessToken that we recover following a login to authenticate in the DRF instance. Currently the JWT verification fails in the django-auth-adfs `validate_access_token()` with:

`Error decoding signature: Signature verification failed`

I note that the 'audience' for the token returned in the Angular-MSAL library is for MS Graph,  (` "aud": "00000003-0000-0000-c000-000000000000" `), i.e. not our Azure 'application' / client id.

Token headers: 

```
{
  "typ": "JWT",
  "nonce": "NOT_49OLXIgUcUN5KGBpE0Hm3oAwkY0V3wuCZ6oeEk4",
  "alg": "RS256",
  "x5t": "l3sQ-50cCH4xBVZLHTGwnSR7680",
  "kid": "l3sQ-50cCH4xBVZLHTGwnSR7680"
}
```

I enabled the debug logs and confirm 3 certificates are loaded, none of them match the access token. 

In order for django-auth-adfs to verify the accessToken returned is there a specific change we need to make in the Azure or in the request for the login ?

thanks and sorry if these are newbie questions  !

-i

**Comment by ivan-price-acted** [comment]
OK responding to my post above, the `accessToken` returned by the Angular-MSAL is not to be used for APIs other than MS Graph, in fact the `idToken` should be used to match the 'resource' (i.e. Front or DRF) application. This is no doubt obvious for non-newbies.

In our case it seems that we are required therefore to provide the backend with the idToken to authenticate incoming API requests, and possibly the `accessToken` in order for the backend to determine groups and other membership infos from (new requests to) the MS Graph API, which aren't returned in the initial login tokens.

I'm not sure what are the ramifications of using the 'frontend' application idToken to auth requests for the backend api however, is this considered bad practice, if so why ?

**Comment by JonasKs** [comment]
Angular MSAL should be able to take multiple client IDs, and that way fetch multiple tokens. It works by fetching an `id_token` and then it silently fetches `access_token`s for all your given client IDs. You’ll then have to use the correct token for the API, based on the client ID. 

I’m unfortunately not a frontend developer, nor ever used Angular so I’m not in a position to help you much, but you’re on the right path, so keep trying 😊

**Comment by ivan-price-acted** [comment]
Thanks for your patience and help @JonasKs . The key point for us was to define and request our *api-specific scope* for interfacing with our API, and associating it with the API URLs in the angular app.

I.e. by configuring the MSAL/Angular library with the following in the 'interceptor' config:

```
    }), {
      interactionType: InteractionType.Redirect,
      protectedResourceMap: new Map([
        ['https://graph.microsoft.com/v1.0/me', ['user.read']],
        ['http://localhost:8000', ['api://2f345207-REDACTED-a0b345454528/core-user']] // -> url root, scope names
      ])
    })
```

Access tokens for our API, (not the MS Graph API) are send with the API url requests (e.g. localhost), and MS urls get the MS access token. Everything is automatic, including redirect to login page so that's cool.

django-auth-adfs is able to validate those tokens out of the box,, using a settings.py config:

```
'AUDIENCE': 'api://2f345207-REDACTED-a0b345454528'
```

thanks again for the terrific library!

-i

**Comment by JonasKs** [comment]
Perfect, happy you solved it :blush: I'll close the issue, but feel free to open a new one/ask further questions here if you have any.

Have a great week!

**Comment by marshad96** [comment]
> Thanks for your patience and help @JonasKs . The key point for us was to define and request our _api-specific scope_ for interfacing with our API, and associating it with the API URLs in the angular app.
> 
> I.e. by configuring the MSAL/Angular library with the following in the 'interceptor' config:
> 
> ```
>     }), {
>       interactionType: InteractionType.Redirect,
>       protectedResourceMap: new Map([
>         ['https://graph.microsoft.com/v1.0/me', ['user.read']],
>         ['http://localhost:8000', ['api://2f345207-REDACTED-a0b345454528/core-user']] // -> url root, scope names
>       ])
>     })
> ```
> 
> Access tokens for our API, (not the MS Graph API) are send with the API url requests (e.g. localhost), and MS urls get the MS access token. Everything is automatic, including redirect to login page so that's cool.
> 
> django-auth-adfs is able to validate those tokens out of the box,, using a settings.py config:
> 
> ```
> 'AUDIENCE': 'api://2f345207-REDACTED-a0b345454528'
> ```
> 
> thanks again for the terrific library!
> 
> -i

Hello @ivan-price-acted  can you help me set this up? I've integrated the Django DRF. Normal login from DRF works but access token from the frontend application (when passed to DRF api header) the Signature Verfication error comes up. Can you help me fix it?

**Comment by ivan-price-acted** [comment]
@marshad96 not sure if you got this working but you should try to determine why the sig verification is failing ..
and verify that your frontend is sending an access token suitable for your backend, not the MS graph backend.. i.e. the `audience` is correct.
