### ISSUE TITLE
Support for client credentials flow with alternate audience from auth code flow in Azure AD

### ISSUE THREAD

**Issue by janmande** [snok/django-auth-adfs#209]
The use case is that a daemon app needs access to a Web API in a Django instance and does not use delegated credentials from a logged on user. Both apps are registered in Azure AD. The Django instance also has a front end where users are logged in with Azure AD.

When the daemon app requests a token it specifies a scope which becomes the audience for the token. The audience value returned is the Application ID URI, which is a URI. This is different than the audience returned from Azure in a token when the [auth code flow](https://docs.microsoft.com/nb-no/azure/active-directory/develop/v2-oauth2-auth-code-flow) is used. In this flow the audience is the appid of the application. Which in Azure AD is a guid.

In the AUTH_ADFS settings, AUDIENCE is a single value, but for this scenario to work I have not been able to find a way to avoid having the Django instance being configured with two different audiences. One for the [auth code flow](https://docs.microsoft.com/nb-no/azure/active-directory/develop/v2-oauth2-auth-code-flow), and one for the [client credentials flow](https://docs.microsoft.com/nb-no/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow).

AUTH_ADFS is configured like this for the auth code flow to work:

```
INSTALLED_APPS = [
   ....
   'django_auth_adfs',
]
AUTHENTICATION_BACKENDS = [
     'django_auth_adfs.backend.AdfsAuthCodeBackend',
     'django_auth_adfs.backend.AdfsAccessTokenBackend',
 ]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        # Guarantees that everyone has to be authenticated for the REST views
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'django_auth_adfs.rest_framework.AdfsAccessTokenAuthentication', # Azure AD
        'rest_framework.authentication.SessionAuthentication',  # User is logged in with the browser
    ),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'
    # https://stackoverflow.com/questions/57123611/why-swagger-raises-unclear-error-django
}

AUTH_ADFS = {
    'AUDIENCE': 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    'CLIENT_ID': 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    'CLIENT_SECRET': '<django app client secret>',
    'CA_BUNDLE': True,
    'CLAIM_MAPPING': {'first_name': 'given_name',
                      'last_name': 'family_name',
                      'email': 'upn'},
    'GROUPS_CLAIM': 'roles',
    'GROUP_TO_FLAG_MAPPING': {
      "is_staff": IS_STAFF_GROUP_ID,
      "is_superuser": IS_SUPERUSER_GROUP_ID
    },
    'DISABLE_SSO': True,
    'MIRROR_GROUPS': True,
    'USERNAME_CLAIM': 'oid',
    'TENANT_ID': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
    'RELYING_PARTY_ID': 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    'CREATE_NEW_USERS': True,
    'LOGIN_EXEMPT_URLS': [
        '^api/',
    ],
    'VERSION': 'v1.0',
    'BLOCK_GUEST_USERS': True,
}

MIDDLEWARE = [
  ....
   'django_auth_adfs.middleware.LoginRequiredMiddleware',
]
# Configure django to redirect users to the right URL for login
LOGIN_URL = "django_auth_adfs:login"
LOGIN_REDIRECT_URL = "/"
```
Here is the code to get token and call Web API from daemon client

```
import json

import jwt
import requests
import logging

try:
    import http.client as http_client
except ImportError:
    # Python 2
    import httplib as http_client
http_client.HTTPConnection.debuglevel = 1

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)
headers = {
    'Accept': 'application/json',
}

# Get an access token
token_payload = {
    "grant_type": "client_credentials",
    "client_id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",  # Client App ID
    "scope": "api://bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb/.default",  # Scope in the API you want to call
    "client_secret": "<client daemon secret>",
}
tenant_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

# Get an access token
logger.debug("Getting token")
response = requests.post(
    f"https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token",
    data=token_payload,
    headers=headers
)
response.raise_for_status()
response_data = response.json()
access_token = response_data['access_token']
decoded_token = jwt.decode(access_token, options={"verify_signature": False})

logger.debug(f"Decoded: {json.dumps(decoded_token, indent=4)}")
logger.debug(f"Token: {access_token}")

# Make a request towards this API
headers = {
    'Accept': 'application/json',
    'Authorization': 'Bearer ' + access_token,
}

response = requests.get(
    'http://localhost:8001/api/resource',
    headers=headers,
    verify=False
)
logging.debug(f"Response: {response}")

```

This returns a token on the following form where aud is on the URI form:
```
{
    "aud": "api://bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
    "iss": "https://sts.windows.net/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/",
    "iat": 1639053766,
    "nbf": 1639053766,
    "exp": 1639057666,
    "aio": "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
    "appid": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
    "appidacr": "1",
    "idp": "https://sts.windows.net/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/",
    "oid": "zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzzz",
    "rh": "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.",
    "sub": "wwwwwwww-wwww-wwww-wwww-wwwwwwwwwwww",
    "tid": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "uti": "qqqq-qqqqqqqqqqqq",
    "ver": "1.0"
}
```

But calling the Web API with this token gives me a 401 and django_auth_adfs logs Invalid audience:
```
django_auth_adfs: INFO     Invalid audience

```

**Is there a way to configure these apps in Azure AD or django-auth-adfs to support both flows in the same Django instance?**

I can make it work buy using an alternate audience for the AdfsAccessTokenBackend when decoding the token, and will be happy to contribute a change if this cannot be achieved in the current code base.

My suggested solution to this would be to include a REST_AUDIENCE in AUTH_ADFS which is used as alternate audience, but which defaults to AUDIENCE if not specified. This audience is used when validating the token in AdfsAccessTokenBackend.

**Comment by JonasKs** [comment]
Seems to me that there’s something iffy going in. You configured Azure AD to use v1 tokens, but when you request a token you go to the v2 token endpoint. Please try to remove the `v2` from the URL. 

In my FastAPI-Azure-Auth package I’ve hard coded this based on token versions: https://github.com/Intility/fastapi-azure-auth/blob/main/fastapi_azure_auth/auth.py#L181

**Comment by janmande** [comment]
Thanks you pointed at what turned out to be the problem. Allthough changing to getting the token from the v1.0 endpoint returns an audience I do not recognize at all:

```"aud": "00000002-0000-0000-c000-000000000000",```

It turns out that the manifest of the application did not specify the access token version, it was set to null. Changing this to version 2 and also setting version 2 in settings.py of Django makes this work. I then get application id of the Web API as audience in the client token.

Application Manifest in Azure AD

```"accessTokenAcceptedVersion": 2,```

settings.py

```
AUTH_ADFS = {
   ...
    'VERSION': 'v2.0',
}
```

**Comment by JonasKs** [comment]
That’s the audience for the Graph API. 

Happy you got it working with v2 though. 😊
