### ISSUE TITLE
When granting user consent initial redirect to /oauth2/callback returns No authorization code was provided.

### ISSUE THREAD

**Issue by Sparrow0hawk** [snok/django-auth-adfs#218]
# Overview

When configuring a django app with with django-auth-adfs using Azure AD using [docs](https://django-auth-adfs.readthedocs.io/en/latest/azure_ad_config_guide.html) the user is initial prompted to consent to using the application. Immediately after consenting the user is redirected to a `Login Failed` page.

The error included in the debug output suggests misconfigured permissions but I am confident the correct permissions are set on Azure.

Curiously when revisiting the django site url after this error I am logged in and able to log in and log out using the associated Office 365 account, it only occurs at this consent step.

## Logs

```
backend_1  | [27/Jan/2022 16:43:43] "GET / HTTP/1.1" 302 0
backend_1  | [27/Jan/2022 16:43:43] "GET /oauth2/login?next=/ HTTP/1.1" 302 0
backend_1  | Bad Request: /oauth2/callback
backend_1  | [27/Jan/2022 16:43:57] "GET /oauth2/callback?error=invalid_request&error_description=AADSTS90008%3a+The+user+or+administrator+has+not+consented+to+use+the+application+with+ID+%273c8e86fb-4fe4-4ff1-8557-11a420e3e989%27(django-arcquiz-backend).+This+happened+because+application+is+misconfigured%3a+it+must+require+access+to+Microsoft+Graph+by+specifying+at+least+%27Sign+in+and+read+user+profile%27+permission.%0d%0aTrace+ID%3a+77e6554a-2589-4069-9daa-0b96c8a62b00%0d%0aCorrelation+ID%3a+df0479b2-4c65-4542-a1ba-a76e2083566c%0d%0aTimestamp%3a+2022-01-27+16%3a43%3a57Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d90008&state=Lw%3d%3d HTTP/1.1" 400 668
```

Whilst this looked similar to (#143) changing the manifest did not resolve this.

Let me know if extra information is required.

**Comment by tim-schilling** [comment]
@Sparrow0hawk please [enable the debug logs](https://django-auth-adfs.readthedocs.io/en/latest/troubleshooting.html#turn-on-django-debug-logging) and check to see if that contains additional information.

**Comment by Sparrow0hawk** [comment]
Apologies @tim-schilling, see below for some examples of the debug logs.

On first visit to the site and when accepting user consent. Get an immediate `No authorization code was provided` error.
```
[31/Jan/2022 15:09:45] "GET / HTTP/1.1" 302 0
DEBUG 2022-01-31 15:09:45,952 django_auth_adfs Loading django_auth_adfs ID Provider configuration.
INFO 2022-01-31 15:09:45,952 django_auth_adfs Trying to get OpenID Connect config from https://login.microsoftonline.com/bdeaeda8-c81d-45ce-863e-5232a535b7cb/.well-known/openid-configuration?appid=3c8e86fb-4fe4-4ff1-8557-11a420e3e989
DEBUG 2022-01-31 15:09:46,227 django_auth_adfs Loading public key from certificate: MIIDBTCCAe2gAwIBAgIQN33ROaIJ6bJBWDCxtmJEbjANBgkqhkiG9w0BAQsFADAtMSswKQYDVQQDEyJhY2NvdW50cy5hY2Nlc3Njb250cm9sLndpbmRvd3MubmV0MB4XDTIwMTIyMTIwNTAxN1oXDTI1MTIyMDIwNTAxN1owLTErMCkGA1UEAxMiYWNjb3VudHMuYWNjZXNzY29udHJvbC53aW5kb3dzLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKGiy0/YZHEo9rRn2bI27u189Sq7NKhInFz5hLCSjgUB2rmf5ETNR3RJIDiW1M51LKROsTrjkl45cxK6gcVwLuEgr3L1TgmBtr/Rt/riKyxeXbLQ9LGBwaNVaJrSscxfdFbJa5J+qzUIFBiFoL7kE8ZtbkZJWBTxHEyEcNC52JJ8ydOhgvZYykete8AAVa2TZAbg4ECo9+6nMsaGsSBncRHJlRWVycq8Q4HV4faMEZmZ+iyCZRo2fZufXpn7sJwZ7CEBuw4qycHvUl6y153sUUFqsswnZGGjqpKSq7I7sVI9vjB199RarHaSSbDgL2FxjmASiUY4RqxnTjVa2XVHUwUCAwEAAaMhMB8wHQYDVR0OBBYEFI5mN5ftHloEDVNoIa8sQs7kJAeTMA0GCSqGSIb3DQEBCwUAA4IBAQBnaGnojxNgnV4+TCPZ9br4ox1nRn9tzY8b5pwKTW2McJTe0yEvrHyaItK8KbmeKJOBvASf+QwHkp+F2BAXzRiTl4Z+gNFQULPzsQWpmKlz6fIWhc7ksgpTkMK6AaTbwWYTfmpKnQw/KJm/6rboLDWYyKFpQcStu67RZ+aRvQz68Ev2ga5JsXlcOJ3gP/lE5WC1S0rjfabzdMOGP8qZQhXk4wBOgtFBaisDnbjV5pcIrjRPlhoCxvKgC/290nZ9/DLBH3TbHk8xwHXeBAnAjyAqOZij92uksAv7ZLq4MODcnQshVINXwsYshG1pQqOLwMertNaY5WtrubMRku44Dw7R
DEBUG 2022-01-31 15:09:46,241 django_auth_adfs Loading public key from certificate: MIIDBTCCAe2gAwIBAgIQWPB1ofOpA7FFlOBk5iPaNTANBgkqhkiG9w0BAQsFADAtMSswKQYDVQQDEyJhY2NvdW50cy5hY2Nlc3Njb250cm9sLndpbmRvd3MubmV0MB4XDTIxMDIwNzE3MDAzOVoXDTI2MDIwNjE3MDAzOVowLTErMCkGA1UEAxMiYWNjb3VudHMuYWNjZXNzY29udHJvbC53aW5kb3dzLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALH7FzF1rjvnZ4i2iBC2tz8qs/WP61n3/wFawgJxUnTx2vP/z5pG7f8qvumd7taOII0aSlp648SIfMw59WdUUtup5CnDYOcX1sUdivAj20m2PIDK6f+KWZ+7YKxJqCzJMH4GGlQvuDIhRKNT9oHfZgnYCCAmjXmJBtWyD052qqrkzOSn0/e9TKbjlTnTNcrIno3XDQ7xG+79vOD2GZMNopsKogWNxUdLFRu44ClKLRb4Xe00eVrANtBkv+mSJFFJS1Gxv611hpdGI2S0v1H+KvB26O7vuzGhZ/AevRemGhXQ5V5vwNEqXnVRVkBRszLKeN/+rxM436xQyVQGJMG+sVECAwEAAaMhMB8wHQYDVR0OBBYEFLlRBSxxgmNPObCFrl+hSsbcvRkcMA0GCSqGSIb3DQEBCwUAA4IBAQB+UQFTNs6BUY3AIGkS2ZRuZgJsNEr/ZEM4aCs2domd2Oqj7+5iWsnPh5CugFnI4nd+ZLgKVHSD6acQ27we+eNY6gxfpQCY1fiN/uKOOsA0If8IbPdBEhtPerRgPJFXLHaYVqD8UYDo5KNCcoB4Kh8nvCWRGPUUHPRqp7AnAcVrcbiXA/bmMCnFWuNNahcaAKiJTxYlKDaDIiPN35yECYbDj0PBWJUxobrvj5I275jbikkp8QSLYnSU/v7dMDUbxSLfZ7zsTuaF2Qx+L62PsYTwLzIFX3M8EMSQ6h68TupFTi5n0M2yIXQgoRoNEDWNJZ/aZMY/gqT02GQGBWrh+/vJ
DEBUG 2022-01-31 15:09:46,241 django_auth_adfs Loading public key from certificate: MIIDBTCCAe2gAwIBAgIQff8yrFO3CINPHUTT76tUsTANBgkqhkiG9w0BAQsFADAtMSswKQYDVQQDEyJhY2NvdW50cy5hY2Nlc3Njb250cm9sLndpbmRvd3MubmV0MB4XDTIxMTAyNDE3NDU1NloXDTI2MTAyNDE3NDU1NlowLTErMCkGA1UEAxMiYWNjb3VudHMuYWNjZXNzY29udHJvbC53aW5kb3dzLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMq979bhE6xX09e87zostNcPJzvtbeu3JomS2catiEg3bXvXcPiMQke5T1dsHs3MyEYHFpmIBZ7JNo+ptdB+LSs3KmTNCSfzYoGNvaRYpsZS+/6lzAdT6KxSXZQCr6eUoI0k8C6145K9QKlsG6cxtsmVDTdxhPBr5k3qOMsHkGzQnfsjv2aaM8dCd+MBwRDLmsPmXwlJO5nSirIPhHBOGb9F4JfcD9jKSj8dFfIC2s8XulEPUoczbq7kjp3KS2CTf6EOGin+abTqda7Hw2NiCvX67ZkUyjnUPjBJknYxi//PCEHLwrO46lc+d1yqF0ZVwfLTCBjnIPiAnq+ssXtorSECAwEAAaMhMB8wHQYDVR0OBBYEFDiZG6s5d9RvorpqbVdS2/MD8ZKhMA0GCSqGSIb3DQEBCwUAA4IBAQAQAPuqqKj2AgfC9ayx+qUu0vjzKYdZ6T+3ssJDOGwB1cLMXMTUVgFwj8bsX1ahDUJdzKpWtNj7bno+Ug85IyU7k89U0Ygr55zWU5h4wnnRrCu9QKvudUPnbiXoVuHPwcK8w1fdXZQB5Qq/kKzhNGY57cG1bwj3R/aIdCp+BjgFppOKjJpK7FKS8G2v70eIiCLMapK9lLEeQOxIvzctTsXy9EZ7wtaIiYky4ZSituphToJUkakHaQ6evbn82lTg6WZz1tmSmYnPqRdAff7aiQ1Sw9HpuzlZY/piTVqvd6AfKZqyxu/FhENE0Odv/0hlHzI15jKQWL1Ljc0Nm3y1skut
INFO 2022-01-31 15:09:46,242 django_auth_adfs django_auth_adfs loaded settings from ADFS server.
INFO 2022-01-31 15:09:46,242 django_auth_adfs operating mode:         openid_connect
INFO 2022-01-31 15:09:46,242 django_auth_adfs authorization endpoint: https://login.microsoftonline.com/bdeaeda8-c81d-45ce-863e-5232a535b7cb/oauth2/authorize
INFO 2022-01-31 15:09:46,242 django_auth_adfs token endpoint:         https://login.microsoftonline.com/bdeaeda8-c81d-45ce-863e-5232a535b7cb/oauth2/token
INFO 2022-01-31 15:09:46,242 django_auth_adfs end session endpoint:   https://login.microsoftonline.com/bdeaeda8-c81d-45ce-863e-5232a535b7cb/oauth2/logout
INFO 2022-01-31 15:09:46,242 django_auth_adfs issuer:                 https://sts.windows.net/bdeaeda8-c81d-45ce-863e-5232a535b7cb/
[31/Jan/2022 15:09:46] "GET /oauth2/login?next=/ HTTP/1.1" 302 0
Bad Request: /oauth2/callback
[31/Jan/2022 15:09:49] "GET /oauth2/callback?error=invalid_request&error_description=AADSTS90008%3a+The+user+or+administrator+has+not+consented+to+use+the+application+with+ID+%273c8e86fb-4fe4-4ff1-8557-11a420e3e989%27(django-arcquiz-backend).+This+happened+because+application+is+misconfigured%3a+it+must+require+access+to+Microsoft+Graph+by+specifying+at+least+%27Sign+in+and+read+user+profile%27+permission.%0d%0aTrace+ID%3a+3f640435-0dde-4827-998b-4271e00e2b00%0d%0aCorrelation+ID%3a+5375c18e-a843-4fb6-a223-886ea6552cec%0d%0aTimestamp%3a+2022-01-31+15%3a09%3a49Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d90008&state=Lw%3d%3d HTTP/1.1" 400 668

```
But on next visit to site authorisation is successful.
```
[31/Jan/2022 15:11:36] "GET / HTTP/1.1" 302 0
[31/Jan/2022 15:11:36] "GET /oauth2/login?next=/ HTTP/1.1" 302 0
DEBUG 2022-01-31 15:11:36,757 django_auth_adfs Received authorization code: XXXXXXXX
DEBUG 2022-01-31 15:11:36,757 django_auth_adfs Getting access token at: https://login.microsoftonline.com/bdeaeda8-c81d-45ce-863e-5232a535b7cb/oauth2/token
DEBUG 2022-01-31 15:11:36,923 django_auth_adfs Received access token: XXXXXXX
DEBUG 2022-01-31 15:11:36,951 django_auth_adfs Attribute 'first_name' for user 'XXXX@XXXX' was set to 'XXXXX'.
DEBUG 2022-01-31 15:11:36,951 django_auth_adfs Attribute 'last_name' for user 'XXXX@XXXXX' was set to 'XXXX'.
DEBUG 2022-01-31 15:11:36,953 django_auth_adfs Attribute 'email' for user 'XXXX@XXXXX' was set to 'XXXXX.
DEBUG 2022-01-31 15:11:36,959 django_auth_adfs The configured groups claim 'roles' was not found in the access token
DEBUG 2022-01-31 15:11:36,959 django_auth_adfs The configured group claim was not found in the access token
[31/Jan/2022 15:11:36] "GET /oauth2/callback?code=XXXXXXXXXXXstate=Lw%3d%3d&session_state=ef5d713e-430d-4204-b0ec-50888bbbfde2 HTTP/1.1" 302 0
[31/Jan/2022 15:11:37] "GET / HTTP/1.1" 200 2813
[31/Jan/2022 15:11:37] "GET /static/main.css HTTP/1.1" 304 0
Not Found: /...
[31/Jan/2022 15:11:37] "GET /... HTTP/1.1" 404 2411
```

**Comment by JonasKs** [comment]
When logging in, what is the URL you are redirected to?

**Comment by Sparrow0hawk** [comment]
First time log in redirects to:
https://login.microsoftonline.com/bdeaeda8-c81d-45ce-863e-5232a535b7cb/oauth2/authorize?response_type=code&client_id=3c8e86fb-4fe4-4ff1-8557-11a420e3e989&resource=3c8e86fb-4fe4-4ff1-8557-11a420e3e989&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Foauth2%2Fcallback&state=Lw%3D%3D&scope=openid

After password submission and 2 factor authenticating i'm shown the Permissions Requested page at
https://login.microsoftonline.com/common/federation/OAuth2ClaimsProvider 

Where after accepting I am redirected to:
http://localhost:8000/oauth2/callback?error=invalid_request&error_description=AADSTS90008%3a+The+user+or+administrator+has+not+consented+to+use+the+application+with+ID+%273c8e86fb-4fe4-4ff1-8557-11a420e3e989%27(django-arcquiz-backend).+This+happened+because+application+is+misconfigured%3a+it+must+require+access+to+Microsoft+Graph+by+specifying+at+least+%27Sign+in+and+read+user+profile%27+permission.%0d%0aTrace+ID%3a+f9fe1118-7d86-4d84-9884-eff0c8f30c00%0d%0aCorrelation+ID%3a+fa86ea0f-c10d-4193-b690-337a1267cf90%0d%0aTimestamp%3a+2022-02-01+13%3a32%3a37Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d90008&state=Lw%3d%3d#

**Comment by Sparrow0hawk** [comment]
@tim-schilling This is what I initially investigated, but I definitely have given those permissions to my app registration on Azure
![image](https://user-images.githubusercontent.com/20887250/151989589-4dfbcc68-2e1a-4435-8d7e-9ae70a68b199.png)
I've set this up following all the steps in the [Azure AD documentation](https://django-auth-adfs.readthedocs.io/en/latest/azure_ad_config_guide.html)

This is the view I get:
![image](https://user-images.githubusercontent.com/20887250/152002140-f5e6d752-b806-45d9-aff5-471fbf41889b.png)

I am also immediately able to navigate to my site from this error page and find I am logged in without any errors, which suggests I haven't misconfigured this Microsoft Graph API setting?

**Comment by JonasKs** [comment]
Did you check `admin and users` for the concent?

https://django-auth-adfs.readthedocs.io/en/latest/_images/14_add_a_scope.PNG

**Comment by Sparrow0hawk** [comment]
Yep
![image](https://user-images.githubusercontent.com/20887250/152010167-0ecc1e02-88aa-4cd3-ac7e-4c816c3d9278.png)

**Comment by JonasKs** [comment]
Please provide the Azure AD manifest of your application, and I'll see if I can spot something.

**Comment by Sparrow0hawk** [comment]
Manifest for backend azure app reg:
```
{
	"id": "2b696fdc-fcb5-4eb1-95e5-7ce05b501c97",
	"acceptMappedClaims": null,
	"accessTokenAcceptedVersion": 1,
	"addIns": [],
	"allowPublicClient": null,
	"appId": "3c8e86fb-4fe4-4ff1-8557-11a420e3e989",
	"appRoles": [],
	"oauth2AllowUrlPathMatching": false,
	"createdDateTime": "2022-01-27T14:16:36Z",
	"description": null,
	"certification": null,
	"disabledByMicrosoftStatus": null,
	"groupMembershipClaims": null,
	"identifierUris": [
		"api://3c8e86fb-4fe4-4ff1-8557-11a420e3e989"
	],
	"informationalUrls": {
		"termsOfService": null,
		"support": null,
		"privacy": null,
		"marketing": null
	},
	"keyCredentials": [],
	"knownClientApplications": [],
	"logoUrl": null,
	"logoutUrl": null,
	"name": "django-arcquiz-backend",
	"notes": null,
	"oauth2AllowIdTokenImplicitFlow": false,
	"oauth2AllowImplicitFlow": false,
	"oauth2Permissions": [
		{
			"adminConsentDescription": "read",
			"adminConsentDisplayName": "read",
			"id": "5d2c4a4f-2d67-41e6-aca7-99d37f92357c",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"type": "User",
			"userConsentDescription": null,
			"userConsentDisplayName": null,
			"value": "read"
		}
	],
	"oauth2RequirePostResponse": false,
	"optionalClaims": null,
	"orgRestrictions": [],
	"parentalControlSettings": {
		"countriesBlockedForMinors": [],
		"legalAgeGroupRule": "Allow"
	},
	"passwordCredentials": [
		{
			"customKeyIdentifier": null,
			"endDate": "2024-01-27T14:17:01.29Z",
			"keyId": "2386fae7-c987-4205-abd9-24032f67a7e4",
			"startDate": "2022-01-27T14:17:01.29Z",
			"value": null,
			"createdOn": "2022-01-27T14:17:18.6781673Z",
			"hint": "vhw",
			"displayName": "djangoQuizSecret"
		}
	],
	"preAuthorizedApplications": [
		{
			"appId": "4e90c7d0-6b2d-40a8-8170-b6a553d30282",
			"permissionIds": [
				"5d2c4a4f-2d67-41e6-aca7-99d37f92357c"
			]
		}
	],
	"publisherDomain": "leeds365.onmicrosoft.com",
	"replyUrlsWithType": [
		{
			"url": "http://localhost:80/oauth2/callback",
			"type": "Web"
		}
	],
	"requiredResourceAccess": [
		{
			"resourceAppId": "00000003-0000-0000-c000-000000000000",
			"resourceAccess": [
				{
					"id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
					"type": "Scope"
				}
			]
		}
	],
	"samlMetadataUrl": null,
	"serviceManagementReference": null,
	"signInUrl": null,
	"signInAudience": "AzureADMyOrg",
	"tags": [],
	"tokenEncryptionKeyId": null
}
```

**Comment by JonasKs** [comment]
I'm not sure, honestly. Could you compare a setup with how I've described it in my FastAPI Azure package, [here](https://intility.github.io/fastapi-azure-auth/single-tenant/azure_setup)?

So only step 1 of the tutorial, but setting token version to `1` and redirect to `http://localhost:80/oauth2/callback`?

**Comment by Sparrow0hawk** [comment]
@JonasKs apologies if i'm misunderstanding my current setup uses `"accessTokenAcceptedVersion": 1` setting and has the redirect uri for the backend set to `http://localhost:80/oauth2/callback`

Should I have a go setting the token version to 2 like in your linked steps?

**Comment by JonasKs** [comment]
No, that should be fine. Just sent the link in case you spotted something else you could investigate. 

I don't really know why Azure is acting up on you 🙁

**Comment by Sparrow0hawk** [comment]
No worries, i'll keep reading/tinkering. It feels like after the user consent acceptance step i'm redirected to the /oauth2/callback url rather than to the originally requested url which is what gives me this error so I think after exhausting your suggestions here it's definitely more Azure side.

**Comment by Sparrow0hawk** [comment]
It looks like this might be a similar issue given i'm doing this from an enterprise level tenant too.

**Comment by Sparrow0hawk** [comment]
Just as a quick update i've raised this as a support ticket via Azure as it seems to be more of an issue with Azure than with the django-auth-adfs plugin. So happy for this ticket to be closed and I can update it if I get any further news from Azure.

**Comment by Gerarddp** [comment]
@Sparrow0hawk Did you ever find out what the issue was?

**Comment by Sparrow0hawk** [comment]
@Gerarddp tragically not, the project using this has hit the back-burner so I haven't had a chance to pursue further.

**Comment by JonasKs** [comment]
You shouldn’t be asked about consent when logging in, though. Please see if [this](https://intility.github.io/fastapi-azure-auth/usage-and-faq/admin_consent_when_logging_in/) or [this](https://github.com/Intility/fastapi-azure-auth/issues/45) works or help you investigate further.

**Comment by Sparrow0hawk** [comment]
Just as a final note on this, after our cloud admins gave this app admin consent this issue has disappeared. 

I suspect it relates to how our Azure directory is configured rather than it being anything to do with this plugin.

**Comment by Gerarddp** [comment]
We've solved the issue by granting the Microsoft Graph permissions as described at the end here https://django-auth-adfs.readthedocs.io/en/latest/azure_ad_config_guide.html#step-3-register-and-configure-an-azure-ad-frontend-application, since we couldn't add them at the start because of lack of permissions. Thank you for the help @JonasKs @Sparrow0hawk
