### ISSUE TITLE
why i can't login through admin panel.

### ISSUE THREAD

**Issue by SashaSotsenko** [snok/django-auth-adfs#222]
When I try to login to the admin panel, I get an invalid username or password warning, but I enter the correct username and password. I would also like to know if I can use the standard authentication and the one you provide together?

**Comment by tim-schilling** [comment]
I think you may have disabled the default authentication backend. What is your [`AUTHENTICATION_BACKENDS`](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-AUTHENTICATION_BACKENDS) setting?

And yes, you can use both if you specify both authentication backends. You can read more on how that works in the [Django docs](https://docs.djangoproject.com/en/4.0/topics/auth/customizing/#customizing-authentication-in-django). If you have specific questions after that, let us know!

**Comment by jamesgrogantech** [comment]
Thanks @tim-schilling I couldn't work this one out and had the same issue as @SashaSotsenko as soon as you add
 ```
AUTHENTICATION_BACKENDS = (
    'django_auth_adfs.backend.AdfsAuthCodeBackend',
)
```
it overides the default setting. This is how I have set mine now:
```
AUTHENTICATION_BACKENDS = (
    'django_auth_adfs.backend.AdfsAuthCodeBackend',
    'django.contrib.auth.backends.ModelBackend',
)
```

**Comment by tim-schilling** [comment]
Closing issue due to lack of response from OP and clear solution from @jamesgrogantech (thanks!)
