### ISSUE TITLE
GUEST_USERNAME_CLAIM not working for Azure AD guest users

### ISSUE THREAD

**Issue by ollipa** [snok/django-auth-adfs#226]
`GUEST_USERNAME_CLAIM` does not seem to be working for Azure AD guest users. According to the documentation, the following has to be true for the guest username claim to be used:

1. A guest_username_claim is configured
2. Token claims do not have the configured settings.USERNAME_CLAIM in it
3. The settings.BLOCK_GUEST_USERS is set to False
4. The claims tid does not match settings.TENANT_ID

The problem is with the criteria number 4. The guest users have the same tenant ID as normal the normal users. Maybe in multi-tenant configuration this is different?

From Azure AD documentation I can see that `idp` claim could be used to identify guest users:
https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#payload-claims

> idp: Records the identity provider that authenticated the subject of the token. This value is identical to the value of the Issuer claim unless the user account not in the same tenant as the issuer - guests, for instance. If the claim isn't present, it means that the value of iss can be used instead. For personal accounts being used in an organizational context (for instance, a personal account invited to an Azure AD tenant), the idp claim may be 'live.com' or an STS URI containing the Microsoft account tenant 9188040d-6c67-4c5b-b112-36a304b66dad.

My configuration:
- django-auth-adfs version 1.9.4
- Azure Active Directory endpoint version 1.0
  - With v2.0 I hit this bug: https://github.com/snok/django-auth-adfs/issues/198

**Comment by JonasKs** [comment]
Hello @ollipa ! Thank you for the well written issue and a PR with it!

I'm unfortunately not able to look into it today, but I'll have a look tomorrow. 😊
