### ISSUE TITLE
Logout Django session once timeout

### ISSUE THREAD

**Issue by EvaYiYang** [snok/django-auth-adfs#228]
I have a requirement when user has been idle long enough, the application should log the user out of Django session, but not AzureAD.

I tried some libraries such as django-session-timeout, but once timeout, it seems django-auth-adfs would take over and re-authenticate the user back into the app, instead of redirecting the user to an dedicated logout page.
It seems to me that Django session did timeout, and log user out, but it would re-authenticate immediately since (probably) the underlying AzureAD session was not timed out.

Is there something I can configure to achieve the requirement. Thank you.

**Comment by JonasKs** [comment]
This is pretty much straight the opposite of what SSO is intended to do. If you sign out from Django -> a forced redirect to ADFS would be performed -> at ADFS the user is signed, so it redirects back to Django -> Django auths the user. This is literally SSO. 

I don’t know whether you can force a sign out for a specific client ID only in ADFS, but that would probably be the way to go. 

Unfortunately, this isn’t really something we can implement.
