### ISSUE TITLE
Request Error "AADSTS900144: The request body must contain the following parameter: 'client_id'"

### ISSUE THREAD

**Issue by gwillig** [snok/django-auth-adfs#231]
Hello,

I followed precisely the tutorial on  page ( [https://django-auth-adfs.readthedocs.io/en/latest/)](https://django-auth-adfs.readthedocs.io/en/latest/). But when I click the button "microsoft" on the site "Django administration"
 I get the error msg 
`"(invalid_request) AADSTS900144: The request body must contain the following parameter: 'client_id'`

I spent more than a day to figure it out how to fix it without any luck. Does anyone has an idea how to fix it?

**Comment by gwillig** [comment]
Does someone know the answer?

**Comment by tim-schilling** [comment]
@gwillig Please provide more information about your setup (versions, AD type, AD setup) and which tutorial you followed.

**Comment by sondrelg** [comment]
Closing from lack of response. Feel free to reopen :slightly_smiling_face:
