### ISSUE TITLE
Not authorized to acces this page

### ISSUE THREAD

**Issue by Mergpijp** [snok/django-auth-adfs#234]
Hey I have read some issues #218 and more but I get a non authorized and a django login screen when I try to login. See picture:

![image](https://user-images.githubusercontent.com/53097999/169289481-1dd86ab8-51ca-4a38-b4b3-16fd0662233a.png)

**Comment by Mergpijp** [comment]
I managed to log in with django.contrib.auth.backends.ModelBackend. But everytime if i log in with my azure account the staff and superuser is not set.

**Comment by JonasKs** [comment]
Please see https://django-auth-adfs.readthedocs.io/en/latest/settings_ref.html#group-to-flag-mapping

**Comment by tim-schilling** [comment]
@Mergpijp that depends on what group you want to use to identify that the user is a staff user. For me it was only security groups, but your AD can be configured differently.

**Comment by Mergpijp** [comment]
So do I understand correctly you need add group to group_to_flag_mapping?
```

    "GROUP_TO_FLAG_MAPPING": {"is_staff": ["Django Staff", "Other Django Staff"],
                            "is_superuser": ["Django Admins", "Security groups"]},
```

Maybe I need Groups and Security?

**Comment by tim-schilling** [comment]
> Maybe I need Groups and Security?

Again, we can't help you there. It's dependent on your set up.

> What source attribute do I need to pick?

I don't understand what you mean by source attribute.

**Comment by Mergpijp** [comment]
I mean in the groups claim edit/creation what to select under customize.

![image](https://user-images.githubusercontent.com/53097999/169327584-b499010c-3975-4780-9d6f-99da34a362d7.png)

**Comment by JonasKs** [comment]
It depends how your Azure is set up. `Access` kan be `sAMAccountName`, but you could also use Azure AD roles (recommended). It all depends on your setup and how you want to manage your application registrations.

**Comment by JonasKs** [comment]
Did you figure it out? 😊

**Comment by Mergpijp** [comment]
I parked this but I saw you recommending roles instead of groups. If I remember correctly.

**Comment by JonasKs** [comment]
Alright 👍  I’ll close this for now then.

**Comment by Mergpijp** [comment]
I added a role in app under active directory > app registration > app roles:

![image](https://user-images.githubusercontent.com/53097999/171213496-49990485-6891-465f-a9b5-fba2be6b5923.png)

I have added my user to the to roll under enterprise applications but I still cannot login into admin.

**Comment by Mergpijp** [comment]
Wait forget my last comment I am looking at Azure AD roles to group. What role is required for superuser or staff?

**Comment by Mergpijp** [comment]
I solved this by making a group in django admin with all permissions and put this group name in the group to flag mapping. Note that a superuser must also be staff if you want the rights. Thanks for your help.
