### ISSUE TITLE
django-auth-adfs is not a registered namespace

### ISSUE THREAD

**Issue by Mergpijp** [snok/django-auth-adfs#246]
When I am trying to open my django home page on a mobile phone I get the above error. Is this known? Why is it working on my laptop and on other laptops?

**Comment by sondrelg** [comment]
I think you forgot to include the error @Mergpijp

**Comment by Mergpijp** [comment]
Ah it needed some time to load I think I resolved this.

**Comment by Mergpijp** [comment]
I think that adfs is not supported on android, so logging in the conventional way makes it work. I just need to add a log in redirect url.

**Comment by Mergpijp** [comment]
The error is attached strange that it does not work on android. Any ideas? I am reopening this again because I thought it worked but it did not.
![Screenshot_2022-07-27-12-42-32-728_com android chrome](https://user-images.githubusercontent.com/53097999/181228442-fbd4f9dd-3740-4dac-bf9b-d7d874c473b4.jpg)

**Comment by JonasKs** [comment]
Django should not care about where you access its site from. You're 100% sure it works on PC?

Try to compare the URL to ADFS between phone and PC.

**Comment by Mergpijp** [comment]
It works because if I login at the admin page I can access the page on phone. It uses conventional login and nog adfs. I checked the url it is the same. Any ideas?

**Comment by Mergpijp** [comment]
Okay I figured it out. On my local development version I have the oauth2 url commented out. Somehow in production it got commented out. However the cookie still worked with adfs on my pc. Saw this because I went incognito. Thanks for the help.
