### ISSUE TITLE
Support for Azure AD B2C

### ISSUE THREAD

**Issue by rogerfn** [snok/django-auth-adfs#248]
Is it possible to use this package it with the Azure AD B2C?

**Comment by JonasKs** [comment]
Haven't tested, so I don't know unfortunately. B2C has a bit different tokens and parameters, and those are atleast not configurable atm.

**Comment by sondrelg** [comment]
For the sake of posterity, did you test it @rogerfn? 

Either way, this seems like it can be closed - hope you agree :slightly_smiling_face: Let us know otherwise

**Comment by rogerfn** [comment]
It is not really compatible, however it is possible to extend the library. I had to write my own authenticator. If you want I can create a PR with this new feature.

**Comment by JonasKs** [comment]
Happy to add that, for sure! So please do. 😊
