### ISSUE TITLE
Django Azure ADFS Issue

### ISSUE THREAD

**Issue by sambuca231** [snok/django-auth-adfs#249]
Hi,

I'm facing issues with the ADFS Django functionality. Can someone help?

LOG:
django_auth_adfs loaded settings from ADFS server.
operating mode:         openid_connect
authorization endpoint: [https://login.microsoftonline.com/xxx
token endpoint:         [https://login.microsoftonline.com/xxx/oauth2/token]
end session endpoint:   [https://login.microsoftonline.com/xxx/oauth2/logout]
issuer:                 [https://sts.windows.net/xxx/](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsts.windows.net%x)
django_auth_adfs authentication backend was called but no authorization code was received

settings.py:

```
AUTH_ADFS = {
    'AUDIENCE': client_id,
    'CLIENT_ID': client_id,
    'RELYING_PARTY_ID': client_id,
    'CLIENT_SECRET': client_secret,
    'CLAIM_MAPPING': {'first_name': 'given_name',
                      'last_name': 'family_name',
                      'email': 'upn'},
    'GROUPS_CLAIM': 'roles',
    'MIRROR_GROUPS': True,
    'USERNAME_CLAIM': 'upn',
    'TENANT_ID': tenant_id ,
    'LOGIN_EXEMPT_URLS': ["api/", "public/"],
    'VERSION': 'v1.0'
}
```

**Comment by JonasKs** [comment]
Please read the [troubleshooting](https://django-auth-adfs.readthedocs.io/en/latest/troubleshooting.html) section.

**Comment by sambuca231** [comment]
That was not really helpfull....anyway I found maybe a point. Concerning the LOG the issuer is: https://sts.windows.net/b914a242-e718-443b-a47c-6b4c649d8c0a/

But within Azure AD it is defined as following:
https://sts.windows.net/b914a242-e718-443b-a47c-6b4c649d8c0a/v2.0

How can I impact only the issuer with the additional required "/v2.0"?

Can you tell me?

Thank you

**Comment by JonasKs** [comment]
This is probably because your token is configured to a  `v2` instead of a `v1`.

**Comment by JonasKs** [comment]
The troubleshooting section is for you to post proper logs to me, with error codes etc.

**Comment by sambuca231** [comment]
Ok, I try it again. Here you can see the endpoints defined in Azure AD APP:
![Endpoints_AD](https://user-images.githubusercontent.com/16293766/186889030-e2e339d4-6ebe-449d-8ca2-14a0311a973c.png)

Here you can see the Log out of django-auth-adfs:
`django_auth_adfs loaded settings from ADFS server.
operating mode:         openid_connect
authorization endpoint: https://login.microsoftonline.com/b914a242-e718-443b-a47c-6b4c649d8c0a/oauth2/v2.0/authorize
token endpoint:         https://login.microsoftonline.com/b914a242-e718-443b-a47c-6b4c649d8c0a/oauth2/v2.0/token
end session endpoint:   https://login.microsoftonline.com/b914a242-e718-443b-a47c-6b4c649d8c0a/oauth2/v2.0/logout
issuer:                 https://login.microsoftonline.com/b914a242-e718-443b-a47c-6b4c649d8c0a/v2.0
msgraph endpoint:       graph.microsoft.com
django_auth_adfs authentication backend was called but no authorization code was received`

So the IDs seems to match? Why is the application not getting an authorization code?

**Comment by sondrelg** [comment]
Closing from lack of response. Feel free to reopen :slightly_smiling_face:
