### ISSUE TITLE
Does Django Admin work?

### ISSUE THREAD

**Issue by Wissperwind** [snok/django-auth-adfs#257]
Hi,

Sorry for opening an issue for the question. But I haven't found the information elswhere.
Is it possible to use this plugin for user authentication for the Django Admin Sites?
I think in that case user objects has to be created for each user in the database. Logging stuff... Will this plugin do this?

**Comment by JonasKs** [comment]
Yes, this works with the Django admin dashboard for login. 

User administration (such as managing the user tables etc) does not.

**Comment by Wissperwind** [comment]
Tanks for the answer
