### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by chiragkanhasoftdev** [snok/django-auth-adfs#260]
Hey

I have followed this link to generate Frontend and Backend app https://django-auth-adfs.readthedocs.io/en/latest/azure_ad_config_guide.html and from #259 

Do i have to use same client_id for Frontend and Backend?

I have below configuration in my backend.

![image](https://user-images.githubusercontent.com/115797625/195850631-68953ee4-34cb-4120-8610-0d6f9974d63b.png)

But when i call API for validate auth_token from Frontend, i am receiving below error.

![image](https://user-images.githubusercontent.com/115797625/195850757-5e8c9a92-1f42-466e-99e2-59dce023757f.png)
![image](https://user-images.githubusercontent.com/115797625/195850893-81514e2c-c3ec-43ea-bd8b-553bef57b270.png)

I have also tried web and SPA within same app

![image](https://user-images.githubusercontent.com/115797625/195853550-25dff828-fa32-49b8-ae26-8f74ab777194.png)

**Comment by chiragkanhasoftdev** [comment]
I set jwt decode option and its decoding as per below screenshot. Here aud, iss are not match, and i think thats the issue. if i change `access_token` to `id_token` then i didn't able to extract `given_name` , `family_name` and `upn`

![image](https://user-images.githubusercontent.com/115797625/195973093-a646020e-5812-418c-8ec0-b1ce46b17b4f.png)

**Comment by JonasKs** [comment]
You must use the access token. 

Seems like your token is for graph (the audience is for graph), so that won’t work.

**Comment by JonasKs** [comment]
Which token you get will often be correlated to the scope you’re using. Ensure the scope is correct.

**Comment by chiragkanhasoftdev** [comment]
Here is the scope that i have in my Reactjs app

```
export const loginRequest = {
    scopes: ["User.Read"]
};
```

Here is the scope which defined in my app

![image](https://user-images.githubusercontent.com/115797625/195976973-1c2206b3-4d36-44c6-a573-a5a7a45bf407.png)

**Comment by chiragkanhasoftdev** [comment]
exactly which permission i have to use in order to resolve this issue?

**Comment by JonasKs** [comment]
You need to _also_ have the scope for your backend app. It’ll be something like:

```
export const loginRequest = {
    scopes: [api://<clientid>/.default, "User.Read"]
};
```

Maybe my FastAPI documentation (which is more recent and 100% Azure focused) will clear things up: https://intility.github.io/fastapi-azure-auth/single-tenant/azure_setup

**Comment by JonasKs** [comment]
In that app we create a custom scope (which you can do to, or use the default one), and then we ensure the SPA requests a token for that scope: https://intility.github.io/fastapi-azure-auth/single-tenant/fastapi_configuration#implementing-fastapi-azure-auth

It's important to note that you'll most likely not need the User.Read etc, if you want to fetch additional data from Graph that can be done through the OBO flow.

**Comment by chiragkanhasoftdev** [comment]
after i change scope to `scopes: [api://<clientid>/.default]` access_token works, But now there is very less information of users. it doesn't have `given_name` , `family_name` and `upn`. Is there any way i can get those information using `/.default` scope?

**Comment by chiragkanhasoftdev** [comment]
Thanks @JonasKs , issue resolved. Thanks for your help.

**Comment by JonasKs** [comment]
Good to hear that! You’re welcome 😊

**Comment by guillaumeldc** [comment]
I have the exact same issue. @chiragkanhasoftdev could you please let me know the steps you took to solve this?
