### ISSUE TITLE
How to enable both adfs login and normal Django login

### ISSUE THREAD

**Issue by abadger1** [snok/django-auth-adfs#261]
The documentation does not cover this. Once you add Django-adfs to your settings file, then the normal /login fails - probable because the adfs middle ware will start to handle some of the login URs.

Happy to add config here - if helpful.

**Comment by JonasKs** [comment]
I’ve never had this use case myself. I’m sure you can have multiple auth providers, but not sure if this implementation supports it. 

You’ll have to look at Django docs and investigate from there.

**Comment by junctionapps** [comment]
Adjust your `settings.py` `AUTHENTICATION_BACKENDS` value to use both backends. Put the Django ModelBackend one first.

```
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'django_auth_adfs.backend.AdfsAuthCodeBackend',
)
```

https://django-auth-adfs.readthedocs.io/en/latest/azure_ad_config_guide.html?highlight=AUTHENTICATION_BACKENDS#step-2-configuring-settings-py

**Comment by JonasKs** [comment]
Thanks, @junctionapps! 😊
