### ISSUE TITLE
Unable to use oauth2/token  endpoint.

### ISSUE THREAD

**Issue by jlcmux** [snok/django-auth-adfs#284]
im trying to use REST API auth.

i use this doc: https://django-auth-adfs.readthedocs.io/en/latest/rest_framework.html

but when i try use /oauth2/token endpoint i got "not found" url. 

i can see 

 oauth2/ ^login$ [name='login']
oauth2/ ^logout$ [name='logout'] 

but not oauth2/ ^token$

i would like to login people from nextjs frontend app on my rest api backend usuing azure ad.  

thank you.

**Comment by JonasKs** [comment]
Hi! Please read [this](https://django-auth-adfs.readthedocs.io/en/latest/oauth2_explained.html). The token is not fetched from the backend, but from Azure AD/ADFS.
