### ISSUE TITLE
why do i need to `CREATE_NEW_USERS`?

### ISSUE THREAD

**Issue by ehudkaldor** [snok/django-auth-adfs#291]
Hi,
why is CREATE_NEW_USERS needed? i am using DRF as API server only (no direct access at all) with azure, and can pass the idToken i get from the frontend to my django DRF backend to validate, successfully.

now, since there is no direct access to django, i'm not looking to track users in the backend, simply validate their token and proceed. however, if i set `CREATE_NEW_USERS`   to false (and the user was not created before, i get  `django_auth_adfs User '...' doesn't exist and creating users is disabled.`

what is the use of a user being created for such a scenario? and if not - can i avoid creating them?

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/snok/django-auth-adfs/issues/291">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/snok/django-auth-adfs/issues/291/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/snok/django-auth-adfs/issues/291/pledge.svg">
</picture>
</a>

**Comment by JonasKs** [comment]
Not sure if I understand what you're asking?

The setting is pretty clearly described in the [docs](https://django-auth-adfs.readthedocs.io/en/latest/settings_ref.html).

**Comment by ehudkaldor** [comment]
This is the documentation:
```
Determines whether users are created automatically if they do not exist.

If set to False, then you need to create your users before they can log in.

```

But my users are already created, in azure. I don't need an entry in the database for the user, but it seems like I cannot avoid it

**Comment by tim-schilling** [comment]
@ehudkaldor It sounds like you want some other type of class to represent the user besides a User model. If that's correct, what you're looking for isn't provided out of the box by django-auth-adfs.

You're effectively trying to remove `django.contrib.auth` entirely from the project. Which is probably fine, but that's outside of the scope of this library.

You can use it for inspiration, or even as a base for your own integration. You might be able to patch something together by subclassing `AdfsAuthCodeBackend` or `AdfsAccessTokenBackend`, then customizing `process_access_token` to only do the authentication and authorization bits.

I'm going to close this as a won't fix.

**Comment by ehudkaldor** [comment]
no, that is fine. i was mostly wondering if it could be done, but i understand now that it cannot, without a major hassle.

my main problem is that it creates credentials, along with user and pass, locally. i don't know if a user can login using those (they should not get the password, anyway), but having it there, without me needing or using it to auth, feels like something that should not be.

**Comment by tim-schilling** [comment]
@ehudkaldor it creates a user record, but they are created with an unusable password. You can confirm this by [reviewing the library's code.](https://github.com/snok/django-auth-adfs/blob/70b97c97d01558bbacd93a32d95976dc1e87cc3c/django_auth_adfs/backend.py#L272-L273)

**Comment by JonasKs** [comment]
Correct, they are not able to use that password. It's a Django built-in 😊
