### ISSUE TITLE
Django ADFS 4.0 only works with Firefox 

### ISSUE THREAD

**Issue by Siebe3271** [snok/django-auth-adfs#296]
I followed the installation guide for ADFS 4.0 and I'm able to receive the expected end results when I use Firefox. However, when using Chrome, I get 'This site can't be reached' at the step where it receives the authorization code. The response looks as follows:

http://server:port/oauth2/callback?code=_L8--eqIaEmJYLPR1N-H9w.Nu2QjdaY2wgTR3jW55ffkWg-8zY.JBBrJC8fy4pE95KeVrVgUutBK44ZYY1BvjtYBNeoOMDihy-Fv28Xd7G_laKqX8NENFs8wQE0r6sYS38s4igu2fCkTod7ddy6UouU4dZldom5wp7YuGwp1VWBqmgEotxsego1r1z-IPNZ8TBeKd3YqubAABbbZ20uXo7KEtqM2nycQsDl462saqFe8_gVqs2E-4Jkcl_AgzZnQk5FgXD4TNmfBO0j8bakEa_uVnv_U148epwx3-1V73v8_BpOZ1jY6AHsj0TH5O7cfGNT3YJ09yDWc7u6GbNaMmjzokGhKI-GnrW5MggcQHHI98uvMAjFtY-TkbsZabQxwXBTttYm-g&state=Lw== 

Does anyone know how this can be solved or has anyone experience similar issues? 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/snok) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/snok/django-auth-adfs/issues/296">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/snok/django-auth-adfs/issues/296/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/snok/django-auth-adfs/issues/296/pledge.svg">
</picture>
</a>

**Comment by tim-schilling** [comment]
That error sounds like it's a browser issue which would be unrelated to the package. Can you share the actual URL it's trying to redirect to that chrome is failing to access? You can strip the sensitive bits

**Comment by Siebe3271** [comment]
Issue can indeed be closed. My application was hosted over HTTP instead of HTTPS, which was causing a problem with the redirect.
