### ISSUE TITLE
Readonly database access mode

### ISSUE THREAD

**Issue by hterik** [snok/django-auth-adfs#302]
As a developer, i would like to use django-auth-adfs, while only having readonly access to the database.

Today this is not possible, because the package is writing things into the DB, like last time of login and session identifiers.

Changing the django `SESSION_ENGINE` to `file` is not enough, there are many other paths inside adfs that expect write-access. I haven't done a full investigation on exactly what it writes, just observed that it does.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/snok) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/snok/django-auth-adfs/issues/302">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/snok/django-auth-adfs/issues/302/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/snok/django-auth-adfs/issues/302/pledge.svg">
</picture>
</a>

**Comment by JonasKs** [comment]
This is not something I want to add personally, it is a lot of functionality around users, sessions etc. 

Sorry.

**Comment by tim-schilling** [comment]
If there are minimal changes for us to support a hook that could support this, then maybe. However, judging from your description of "there are many other paths inside adfs that expect write-access", this seems out of scope for what can be invested for development.
