### ISSUE TITLE
Support for Django 5

### ISSUE THREAD

**Issue by dicknetherlands** [snok/django-auth-adfs#311]
Django 5 has been released but django-auth-adfs supports only versions up to 4.2. Is there a roadmap/timeline for adding Django 5 support?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/snok) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/snok/django-auth-adfs/issues/311">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/snok/django-auth-adfs/issues/311/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/snok/django-auth-adfs/issues/311/pledge.svg">
</picture>
</a>

**Comment by tim-schilling** [comment]
I think right now it's when someone has time to do it. I have no reason to
think there's a break. We probably just need to update the test suite,
classifies and cut a new release. If you'd like to help that along, you
could create a PR for the first two tasks.

**Comment by dicknetherlands** [comment]
> I think right now it's when someone has time to do it. I have no reason to think there's a break. We probably just need to update the test suite, classifies and cut a new release. If you'd like to help that along, you could create a PR for the first two tasks.

No problem. PR created. I removed Python 3.7 support too because the tests were no longer able to install or run it, and fixed a linting issue  (Duplicating some work from https://github.com/snok/django-auth-adfs/pull/307 in order to get tests to run!). Tests seem to be passing but for some reason coverage is not? Looking hopeful though.

**Comment by tim-schilling** [comment]
@dicknetherlands thank you for your help. This is being released today.
