### ISSUE TITLE
Django admin UI page: Oauth 2 isn't working

### ISSUE THREAD

**Issue by sbordiya** [snok/django-auth-adfs#326]
I've a django angular application. The accessTokenAcceptedVersion =1 on my azure app manifest works for django admin (http://localhost:8000/admin) but when I change it to version accessTokenAcceptedVersion =2 it stops authenticating and shows me message as "login failed".

I'm using MSAL for the angular side which works with accessTokenAcceptedVersion =2. How do i enable django side to work Oauth 2.0? Here is my stack:

Python== 3.9.18
Django==3.2.*
angular==15.2
msal-angular==2.5.8

Thank you!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/snok) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/snok/django-auth-adfs/issues/326">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/snok/django-auth-adfs/issues/326/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/snok/django-auth-adfs/issues/326/pledge.svg">
</picture>
</a>

**Comment by tim-schilling** [comment]
Closing this due to staleness of the issue. @a-kuchinski, I realize you expect help from this issue, but the logs and information present isn't enough here. It seems like you created a separate issue though, so perhaps we'll continue there.
