### ISSUE TITLE
Claim not found in access token: 'given_name'. Check ADFS claims mapping.

### ISSUE THREAD

**Issue by romuluc** [snok/django-auth-adfs#331]
Sorry if this is trivial. But I'm breaking my head to finish this integration.

Following the **Azure** guide in the Docs I believe the authentication worked.

However, when trying to claim given_name in the access_token, to create the user in my application, the information is not found. Even though I declared it in the token configuration.

![image](https://github.com/snok/django-auth-adfs/assets/16928207/12bed5f7-78cd-4ba5-ad07-4a2db93c682c)

**Token configuration:**
![image](https://github.com/snok/django-auth-adfs/assets/16928207/640c7c7b-4956-48d6-877b-cdedc493041b)

Here are some details of my settings:

```
client_id = os.environ.get('CLIENT_ID')
client_secret = os.environ.get('CLIENT_SECRET')
tenant_id = os.environ.get('TENANT_ID')

AUTH_ADFS = {
    'AUDIENCE': client_id,
    'CLIENT_ID': client_id,
    'CLIENT_SECRET': client_secret,
    'CLAIM_MAPPING': {'first_name': 'given_name',
                      'last_name': 'family_name',
                      'username': 'email'},
    'GROUPS_CLAIM': 'roles',
    'MIRROR_GROUPS': False,
    'USERNAME_CLAIM': 'upn',
    'TENANT_ID': tenant_id,
    'RELYING_PARTY_ID': client_id,
}

AUTHENTICATION_BACKENDS = (
    'django_auth_adfs.backend.AdfsAuthCodeBackend',
)

LOGIN_URL = "django_auth_adfs:login"
LOGIN_REDIRECT_URL = "/"
```

**Azure API Permissions:**
![image](https://github.com/snok/django-auth-adfs/assets/16928207/b9096621-8b76-4dd5-bcfd-11cdceb5dd03)

When I check the access token at https://jwt.io/, in fact the **given_name** is not there.

Stack trace:
```
The configured groups claim roles was not found in the access token
Internal Server Error: /oauth2/callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_auth_adfs/views.py", line 40, in get
    user = authenticate(request=request, authorization_code=code)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 77, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_auth_adfs/backend.py", line 402, in authenticate
    user = self.process_access_token(access_token, adfs_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_auth_adfs/backend.py", line 181, in process_access_token
    self.update_user_attributes(user, claims)
  File "/usr/local/lib/python3.11/site-packages/django_auth_adfs/backend.py", line 301, in update_user_attributes
    raise ImproperlyConfigured(msg.format(claim))
django.core.exceptions.ImproperlyConfigured: Claim not found in access token: 'given_name'. Check ADFS claims mapping.
Internal Server Error: /oauth2/callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_auth_adfs/views.py", line 40, in get
    user = authenticate(request=request, authorization_code=code)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 77, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_auth_adfs/backend.py", line 402, in authenticate
    user = self.process_access_token(access_token, adfs_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_auth_adfs/backend.py", line 181, in process_access_token
    self.update_user_attributes(user, claims)
  File "/usr/local/lib/python3.11/site-packages/django_auth_adfs/backend.py", line 301, in update_user_attributes
    raise ImproperlyConfigured(msg.format(claim))
django.core.exceptions.ImproperlyConfigured: Claim not found in access token: 'given_name'. Check ADFS claims mapping.
```

Do I still need to adjust anything in the Azure Portal?

I'm glad for any help.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/snok) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/snok/django-auth-adfs/issues/331">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/snok/django-auth-adfs/issues/331/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/snok/django-auth-adfs/issues/331/pledge.svg">
</picture>
</a>

**Comment by JonasKs** [comment]
I've never tried to add these claims in Azure, but I suspect they're not behaving like ADFS, and the key will be omitted if the user has not been assigned the values. 

Have you ensured the user actually has a given name set?   
Not much this library can do, if the token isn't providing everything we need. The alternative would be to use OBO flow and fetch more information from graph.

**Comment by tim-schilling** [comment]
If you're using [v1 these claims would be there automatically](https://learn.microsoft.com/en-us/entra/identity-platform/access-token-claims-reference#v10-basic-claims). The docs link you to https://learn.microsoft.com/en-us/entra/identity-platform/optional-claims for v2. It looks like you have followed that for part of it at least. It's hard to decipher what exactly needs to be setup though.

Are you sure you're using the version you think you are? The adfs config in your app doesn't call out version 2 hence my confusion.

**Comment by romuluc** [comment]
> Nunca tentei adicionar essas declarações no Azure, mas suspeito que elas não estejam se comportando como ADFS, e a chave será omitida se os valores não tiverem sido atribuídos ao usuário.
> 
> Você garantiu que o usuário realmente tenha um determinado nome definido? Não há muito que esta biblioteca possa fazer se o token não fornecer tudo o que precisamos. A alternativa seria usar o fluxo OBO e buscar mais informações no gráfico.

Hi @JonasKs ,

You were right. Although the user was registered in the Azure Portal, the claim attributes were not defined in the base registration. The information needed should be defined in Properties.


> If you're using [v1 these claims would be there automatically](https://learn.microsoft.com/en-us/entra/identity-platform/access-token-claims-reference#v10-basic-claims). The docs link you to https://learn.microsoft.com/en-us/entra/identity-platform/optional-claims for v2. It looks like you have followed that for part of it at least. It's hard to decipher what exactly needs to be setup though.
> 
> Are you sure you're using the version you think you are? The adfs config in your app doesn't call out version 2 hence my confusion.

Hi @tim-schilling , I set the correct version in my settings and authentication worked as expected!

Thank you very much guys for the quick replies!

**Comment by tim-schilling** [comment]
I'm glad you were able to solve the problem!
