### ISSUE TITLE
Support for Django 3.2 removed?

### ISSUE THREAD

**Issue by dcleveng** [snok/django-auth-adfs#332]
I'm a little confused about the latest update, 1.13.0. The project documentation on [https://pypi.org/project/django-auth-adfs/](url) seems to suggest that Django 3.2 is still supported, but when I try to update to the latest django-auth-adfs it requires at least Django 4.0. 

Error message: 
`django-auth-adfs 1.13.0 requires django<6,>=4;`

Just want to confirm if Django 3.2 is no longer supported. 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/snok) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/snok/django-auth-adfs/issues/332">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/snok/django-auth-adfs/issues/332/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/snok/django-auth-adfs/issues/332/pledge.svg">
</picture>
</a>

**Comment by tim-schilling** [comment]
1.13.0 is the last release to support Django 3.2

**Comment by tim-schilling** [comment]
I did forget to create the github release for 1.14.0, so I did that just now. The pypi.org page for the project doesn't mention 3.2 from what I can see.

**Comment by tim-schilling** [comment]
Ah, it was me not creating the release. Whoops. Closing the issue as it's made the docs consistent now. Let me know if there's any other questions.
