### ISSUE TITLE
Change port of adfs callback url

### ISSUE THREAD

**Issue by JanSchmidPD** [snok/django-auth-adfs#335]
My Setup is very simple, I have 2 Django apps running on the same maschine behind nginx. One is called by port 80 and one is called by port 82. My problem is now that after adfs login I am always redirected to port 80 for both apps. For the app running behind port 80 that is fine, but not for the one behind port 82. 

How do i change the port of the callback url, so that for one app the user is redirected to host:80  and to host:82 for the other? As far a I was able to research that url is "generated" by django itself and only has to be allowed by the adfs.

I followed the tutorial in the docs to set everything up, so I dont think it helps much if I provide any code.

Thanks for the help.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/snok) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/snok/django-auth-adfs/issues/335">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/snok/django-auth-adfs/issues/335/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/snok/django-auth-adfs/issues/335/pledge.svg">
</picture>
</a>

**Comment by tim-schilling** [comment]
I suspect instance serving this doesn't know it's running on port 82. Here's the relevant part of the project that generates the redirect url. https://github.com/snok/django-auth-adfs/blob/master/django_auth_adfs%2Fconfig.py

Your django app that's handling requests will have to know it's on port 82.

**Comment by tim-schilling** [comment]
Although maybe I'm misunderstanding you. This part may be what you're looking for https://github.com/snok/django-auth-adfs/blob/master/django_auth_adfs%2Fconfig.py#L340-L342

**Comment by JanSchmidPD** [comment]
Thank you very much for your answer. Thanks to your answer I was able to pin down the changes needed. 

In debug mode I was able to see that NGINX sets the host:port part of the redirect url. So i just had to change the follow line in my nginx config (just in case someone has the same problem):

> proxy_set_header Host $host; -> proxy_set_header Host $host:82;
