### ISSUE TITLE
Change default branch to main

### ISSUE THREAD

**Issue by tim-schilling** [snok/django-auth-adfs#347]
Can we switch from master to main for the main branch on the repo? It's something that's bothered me for a while.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/snok) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/snok/django-auth-adfs/issues/347">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/snok/django-auth-adfs/issues/347/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/snok/django-auth-adfs/issues/347/pledge.svg">
</picture>
</a>

**Comment by JonasKs** [comment]
Yes, absolutely.
