### ISSUE TITLE
How to mock or by-pass SSO for testing

### ISSUE THREAD

**Issue by vanderzielj** [snok/django-auth-adfs#350]
Hi folks,

I am using django-auth-adfs v. 1.13.0 with Django 4.2.0 and Azure Entra for single sign-on

- django_auth_adfs.urls included in urlpatterns
- LOGIN_URL = "django_auth_adfs:login"
- Sign In pages links set to 'django_auth_adfs:login' in the base template.

I would like to test all of my views while completely ignoring django-auth-adfs and relying instead on the default Django authorization. What is the best way to accomplish this?

I have a test settings file where I have tried to prevent django-auth-adfs from loading:

- INSTALLED_APPS = list(BASE_INSTALLED_APPS)
- INSTALLED_APPS.remove("django_auth_adfs")
- MIDDLEWARE = list(BASE_MIDDLEWARE)
- MIDDLEWARE.remove("django_auth_adfs.middleware.LoginRequiredMiddleware")
- AUTHENTICATION_BACKENDS: list[Any] = []
- LOGIN_URL = "account_login"
- I set the root url config to the application URLs that excludes the django-auth-adfs.urls

Even after all of this, however, debug shows that i am *still* getting redirectred to `/oauth2/login?next=/orgs/1`

Any suggestions? Could it be that somehow the top-level URLs are still being included?

Regards,

Justin

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/snok) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/snok/django-auth-adfs/issues/350">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/snok/django-auth-adfs/issues/350/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/snok/django-auth-adfs/issues/350/pledge.svg">
</picture>
</a>

**Comment by tim-schilling** [comment]
I think the main thing you'd have to change is `AUTHENTICATION_BACKENDS` so that it has the default value. It shouldn't be empty otherwise it won't know how to look up a user based on any type of authentication and it'll always be treated as logged out. Or I would assume as such.

**Comment by vanderzielj** [comment]
That was the missing piece! Thank you, @tim-schilling

**Comment by vanderzielj** [comment]
To expanding on my `test.py` settings above and explain with more detail for any users who might be wondering how to do this - 

Instead of setting the `AUTHENTICATION_BACKENDS` to an empty array in my settings you should set this explicitly to the default as @tim-schilling suggested:

```
AUTHENTICATION_BACKENDS = ["django.contrib.auth.backends.ModelBackend"]
```

In addition, unless you specify `Debug = True` in your tests you should add the `testserver` to your `ALLOWED_HOSTS`:

```
ALLOWED_HOSTS = ["localhost", "0.0.0.0", "127.0.0.1", "testserver"]
```

Finally, don't forget to create a user (User if using the default Django User model or your defined user e.g. `MySpecialUser` if you use one) and login during your view test setup:

```
class MyViewTestCase(TestCase):

    test_external_credentials = {
        "username": "testuser",
        "password": "testpassword",
    }
    @classmethod
    def setUpTestData(cls):
        cls.user = MySpecialUser.objects.create_user(
            email=cls.test_external_credentials["email"],
            password=cls.test_external_credentials["password"],
        )
```

And then login successfully before testing your view:

```
    def test_view_exists_at_correct_uri(self):
        result = self.client.login(
            email=self.test_external_credentials["email"],
            password=self.test_external_credentials["password"],
        )

        if result:
            response = self.client.get("/expected_view_uri")
            self.assertEqual(response.status_code, 200)

```

**Comment by vanderzielj** [comment]
I just realized that I was successfully running all of my tests - including the views - with my default settings rather than my test settings and that when i tried to run them using my test setting - which disable django-auth-adfs - the view test failed. But I suspect that is because I have the following tag littered through-out my base templates:

```
                                                <a id="log-in-link" class="btn dropdown-item d-flex align-items-center"
                                                   href="{% url 'django_auth_adfs:login' %}">{% translate "Sign In" %}</a>
```

Any suggestions for abstracting this login URL out so that I can continue down this route of disabling ADFS for my unit tests?

Regards,
Justin

**Comment by tim-schilling** [comment]
I'm not quite sure what you're looking for.

**Comment by vanderzielj** [comment]
@tim-schilling do you know of any non-specific Tag I could use in place of `django_auth_adfs:login` that would allow the re-direct to happen when the package is enabled but not require that I replace the tag during testing? Or perhaps is there a way to point Django unit tests at alternate templates? I am a bit new to this (< year) so I probably should be using a technique of which I and just not aware.

Regards, 
Justin

**Comment by tim-schilling** [comment]
What about writing your own view that wraps django-auth-adfs so that you can mock it for testing and pass through to adfs in non-testing?

**Comment by vanderzielj** [comment]
Hey @tim-schilling - that idea sounds interesting and seems possible but I don't know how I would do that at this point. I am going to ask a follow-up question and I think they are related - perhaps even the same.

In my settings for my non-testing environment (i.e. regular settings) I have 

```
LOGIN_URL = "django_auth_adfs:login"
```

which I change to 

```
LOGIN_URL = "account_login"
```

It seems to me that if there was a way to simply reference the value of `LOGIN_URL` in my templates  - like 

```
<a id="log-in-link" class="btn dropdown-item d-flex align-items-center"
  href="{% url 'settings.LOGIN_URL' %}">{% translate "Sign In" %}</a>
```

Then I would have jumped the last hurdle. Do I need to create a view-wrapper to do this or is there another way?

**Comment by vanderzielj** [comment]
An example approach it to create a custom tag that allows me to access the login url setting like the one described in a [StackOverflow post](https://stackoverflow.com/a/7716141/289825) then I could access the `LOGIN_URL` setting like this:

```
{% settings_value "LOGIN_URL" %}
```

Or I suppose I might introduce a context processor that sets a variable `login_location=settings.LOGIN_URL` and then I could access it via the `url` tag (based on [another StackOverflow post](https://stackoverflow.com/a/52290421/289825)) like this: 

```
<a id="log-in-link" class="btn dropdown-item d-flex align-items-center"
  href="{% url login_location %}">{% translate "Sign In" %}</a>
```

Am I overthinking this?

**Comment by tim-schilling** [comment]
Sorry @vanderzielj, you should try asking on the django forum or django discord for generalized help. I don't have the availability to dive in deep into this problem with you. There are a few ways to solve this, but I'm not sure of the implications and they'll depend on your goals. That's why I can't say definitely which way is best.

**Comment by vanderzielj** [comment]
@tim-schilling I was able to implement a context processor and make it work. I tried to explain what I did above in the hope that it will help some other user of the `django-auth-adfs` package and help others to use this fantastic app. Thank you for all of your work on this and for making it available for others to use.
