### ISSUE TITLE
AADSTS500112: The reply address 'domain.com/oauth/callback /?code=XXXXXXXXXXX' does not match the reply address 'https://domain.com/backend/oauth/callback/' provided when requesting Authorization code. 

### ISSUE THREAD

**Issue by chilusoft** [snok/django-auth-adfs#354]
I am thinking this is because of the added query params to the callback URL

the additional details are as follows

this what I am getting in the response json

```
{
    "error": "invalid_client",
    "error_description": "AADSTS500112: The reply address 'https://domain.com/backend/oauth_rdr/?code=XXXXXXXXXXXXXXXXXXXXXXXXXXXX' does not match the reply address 'https://domain.com/backend/oauth_rdr' provided when requesting Authorization code. Trace ID: bfa3ea02-d431-4437-942b-2e9491990b00 Correlation ID: def686cc-7e43-42f1-8c96-9da75e353643 Timestamp: 2024-10-30 01:33:11Z",
    "error_codes": [
        500112
    ],
    "timestamp": "2024-10-30 01:33:11Z",
    "trace_id": "bfa3ea02-d431-4437-942b-2e9491990b00",
    "correlation_id": "def686cc-7e43-42f1-8c96-9da75e353643"
}

```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/snok) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/snok/django-auth-adfs/issues/354">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/snok/django-auth-adfs/issues/354/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/snok/django-auth-adfs/issues/354/pledge.svg">
</picture>
</a>

**Comment by tim-schilling** [comment]
I think this is because Active directory / Entra does not like trailing slashes. You should check your urls.py file that is being used for that path.

**Comment by chilusoft** [comment]
Let me try without the slashes, but do you also think the query parameters can have an effect??

**Comment by JonasKs** [comment]
Did it stop working after an upgrade? I don't think the query parameters should matter here. The code query parameter is what Azure sends us, and we exchange for a token.

**Comment by chilusoft** [comment]
I opted to manually do the SSO integration with the msal python module. But thanks for your time.
